### PR TITLE
Remove redundant depth argument from x_con_init().

### PR DESCRIPTION
**Pull request by Airblader**

### CODE REVIEW

**Comment by stapelberg** [comment]
Is this going to make the possible revert discussed in #2316 harder? If yes, I’d like to wait with merging.

**Comment by Airblader** [comment]
Since we don't need to revert the entire commit I think there's no overlap here, but given that this is just a tiny cleanup, let's wait just to be on the safe side.

**Comment by Airblader** [comment]
@stapelberg We know now that this won't conflict even if we were to do the partial revert, so we can merge it, I think.

**Comment by yshui** [comment]
Uhm, sorry. As the author of the original change, I'm asking why are you removing this?

This is needed if we are not going to use 32-bit depth for all windows (which is the revert you are talking about, right?).

**Comment by Airblader** [comment]
No, see the comment above. Since we wouldn't need to revert entirely, this won't conflict.

**Comment by yshui** [comment]
What part are you planning to revert? You are going to revert to a state where no frame window is using the 32bit depth?

**Comment by Airblader** [comment]
We're currently not planning on reverting anything. We are keeping the option open if more problems arise, but as of now, after many months of 4.12, only a single Raspberry user has reported issues. So IMHO there's no need for the revert right now. The patch that "reverts" support is described in the issue linked above.

**Comment by yshui** [comment]
That makes sense.

Thanks.

**Pull request merged**
