### PR TITLE
Set `_NET_FRAME_EXTENTS` based on border width

### LINKED ISSUE #4292: Set _NET_FRAME_EXTENTS
## I'm submitting a…

<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

_NET_FRAME_EXTENTS property is ~set to all 0s~ not set, even if i3 border size is not 0.

## Desired Behavior

_NET_FRAME_EXTENTS being set properly

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.19 (2020-11-15) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.19 (2020-11-15) (pid 30702)
Loaded i3 config: /home/shui/.config/i3/config (Last modified: Mon 08 Jun 2020 02:41:57 PM BST, 17240827 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

### PR DESCRIPTION
**Pull request by SimonBrandner**
Fixes https://github.com/i3/i3/issues/4292

<hr>

209577166-bf5a934e-62c2-44ee-842f-aa90c3aff352
209577183-7475224e-bac0-41bf-ba7e-611da3cacdc5
209569688-53c8bed3-0023-4b28-baf9-499501261e68
209569716-877721a2-4977-4746-b248-12bb1e20ab1d

<hr>

While this doesn't work perfectly in the tabbed layout, I think it still does much better than the broken thing we have now

I attempted to make the tabbed layout look nicer but I don't know how to actually do that, to be honest

<hr>

Would this solution be acceptable?

### CODE REVIEW

**Comment by SimonBrandner** [comment]
Hello, this PR hasn't received any review yet, is there a reason for that? Is there anything I could do to move it forward?

**Review by orestisfl — CHANGES_REQUESTED** [review]
Thank you for your PR and sorry for the delayed review.

- [x] Please update the [`release-notes/changes/`](https://github.com/i3/i3/tree/next/release-notes/changes) folder with a short description of what changed
- [ ] Some tests here would be beneficial
- [ ] We should figure out a way to improve the tabbed situation. I played with your patch and it seems that if I set a custom border (e.g. `border pixel 50`) to a window and then make it tabbed the frame extents are still reporting `50` even though the tabbed container has different borders

**Comment by SimonBrandner** [comment]
Hello again, I currently don't have the bandwidth to finish the two remaining tasks here, sorry - I would either suggest that someone takes over or the PR is merged as is (if that is something acceptable)

**Comment by MrFox131** [comment]
Any chance this will be merged ever?

**Comment by orestisfl** [comment]
Sure, if somebody picks up the PR and addresses the problem with the tabbed/stacked windows. Since this has been stale for a while I am going to close it for now but please, do open up a follow up if you are interested.

**Comment by MrFox131** [comment]
> Sure, if somebody picks up the PR and addresses the problem with the tabbed/stacked windows. Since this has been stale for a while I am going to close it for now but please, do open up a follow up if you are interested.

I'm very and very interested. But i'm afraid i don't have enough experience in such a big applications on C, and linux under-the-hood things. But I'm experienced developer in other directions. So if you could give me a list of links that would help further my understanding of the current architecture of the repository, and clarify what tests I would like to see, I would be happy to try to look into this issue. I’ve been looking for a long time for an open source project that I could join as a contributor on an ongoing basis. Perhaps this will be the first step)

P.S. I'm too tired to translate from my native language, so there may be mistakes, I apologize for that

**Comment by MrFox131** [comment]
And I also need some instructions how to install it on my system and not to brake everything. Currently I use i3 package from arch repos. But I think it's not gonna be too complicated

**Comment by MrFox131** [comment]
@SimonBrandner I forked repo and installed patched version and cannot clearly understand where is the issue with tabbed mode.My flow is as follows:
1. Opened 2 terminals in horizontal split
2. i3-msg border pixel 10
3. Changed layout to tabbed. 
I cannot see any border width changes due to this layout change. And of course xprops responds with still right _NET_FRAME_EXTENTS 10, 10, 10, 10

**Comment by SimonBrandner** [comment]
Could you share a screenshot please?

**Comment by MrFox131** [comment]
@orestisfl 

@SimonBrandner, sorry btw. I used your handle in my last comment by accident, i meant orestifl
image
image
image
image


1. Just my default splith two alacritty terminals
2. Set left one to 15 pixels border. xprop output provided. Do not look at not rounded borders, 15 is just bigger than my picom config roundness
3. Left terminal xprop output after $mod+w for tabbed layout
4. Right terminal xprop output after $mod+w for tabbed layout

Yes, it's ugly with such a big border size and frame closing by its body top border, but all borders and _NET_FRAME_EXTENTS are in sync

**Comment by MrFox131** [comment]
Any updates? @orestisfl 

I have a lot of work to do next week. If possible, I would like to have time to make my contribution to the development of my favorite tiling manager before this moment, so any comments about tests and inconsistency of frame width in props and i3 state would be appreciated

UPD: No need in comments about tests. Nailed it

**Comment by MrFox131** [comment]
@orestisfl It would be great to get some additional info about this pr. Waiting for the answer

**Comment by SolsticeSpectrum** [comment]
I've been using this for several days now and it works flawlessly and it also looks awesome, I don't use titlebars so I don't care if it has issues. Anyway there is a small issue with Steam and Nautilus (didn't find it in any other app yet)

image
image
As you can see Nautilus and Steam adds a border to compensate for the rounded corner which looks bad

Other apps work flawlessly, even apps running inside wine/Proton have corner radius applied correctly, this just shows how stable this PR is.

You should reopen this PR and continue the work, it works perfectly fine expect Nautilus and Steam

**Comment by ahfriedman** [comment]
I'm also seeing what the previous comments have mentioned wherein the windows in tabbed/stacked mode are rounded, and the tabs themselves are not as shown in the following screenshots (which, to me, seems fine and a big improvement). 

Screenshot_2023-12-29-12-15-27_1920x1080
Screenshot_2023-12-29-12-16-18_1920x1080

Re: the problem with Nautilus., If I understand correctly, I don't think that this is the fault of Nautilus, but instead the GTK theme. Prior to trying this patch, I noticed similar borders and disabled them via the GTK theme. I can try to dig up and send resources related to that if you are interested; however, for now, here's a screenshot of Nautilus running with this patch without such bars showing up. 

Screenshot_2023-12-29-12-18-59_1920x1080

The one thing; however, I did notice is that sometimes with picom, when a single window takes up the whole screen, the borders appear to be the color of the background application (as shown in the following screenshots). This, however, could be a quirk of my setup. 

Screenshot_2023-12-29-12-23-20_1920x1080
Screenshot_2023-12-29-12-23-39_1920x1080

**Comment by SolsticeSpectrum** [comment]
@ahfriedman I don't have the same issue of single app casting different color, maybe it's a setting in i3 config? Try tinkering with bolder colors, there are several active, inactive, focused etc.

Could you send the fix for Nautilus?

And the rounded title bar doesn't irritate me as I don't use them anyway, other than that I've been running this patch for over a month and didn't find any issues other than the one with tabbed and that's basically it

**Comment by ahfriedman** [comment]
Oh awesome! As it seems then that those bugs are resolved, I'd offer to try to help out writing the test cases needed to move the PR forward (after all, there are a few other simple features I'd be interested in trying to add to i3 as well), but having not contributed to i3 before, I'd have to look into how to go about that and see what's needed before committing. 

@DarkReaper231 Here's what I've found works for nautilus and other gtk apps. As it is tangential, I have it in a spoiler:

<details>
  <summary>GTK App Border Fix</summary>
  
[Per https://github.com/i3/i3/issues/1655](https://github.com/i3/i3/issues/1655#issuecomment-92135850), I found that editing `~/.config/gtk-3.0/gtk.css` and adding the following removed the duplicate border. You may, however, have to relog/restart for the changes to take effect.
  
  ```css
.window-frame {
    box-shadow: 0 0 0 0;
    margin: 0;
}

window decoration {
    margin: 0;
    padding: 0;
    border: none;
}
  ```
  
</details>

**Comment by SolsticeSpectrum** [comment]
@ahfriedman unfortunately the fix didn't help, but I think I found the reason
image
the border isn't acutally a border, it's the resize handle, when I hover my cursor over it, a resize cursor appears, this is obviously useless in i3

**Comment by SolsticeSpectrum** [comment]
@ahfriedman I fixed it with some more CSS, specifically:
```css
window.solid-csd {
  padding: 0;  /* removes the padding */
  border: none;  /* removes the border */
  box-shadow: none;  /* removes the double border */
}
```

**Comment by MrFox131** [comment]
Any updates on this pr? If I can help, just give me kinda "task") I'm newbie in contribution to opensource and need some guidance, but certainly can help

**Comment by sigprof** [comment]
I made a different PR for this (#5944) which actually sets the `_NET_FRAME_EXTENTS` values to match the decoration sizes used by i3, so that things like title bars and custom border sizes are handled correctly.  The problem with stacked/tabbed containers looks unsolvable though (at least without some major changes in the way how i3 draws decorations for such containers).

**Comment by ahfriedman** [comment]
To follow up on my above comment, the issue with the borders changing color when a single app is full screen has to do with enabling `smart_borders`. Not sure if the change in https://github.com/i3/i3/pull/5944 would help address it (or if it's just part of how i3 functions in general—its been a bit too long since I've been on the release branch for me to remember).

With respect to the window decorations in stacked/tabbed mode, while I don't think its a huge deal as is, for my own setup, I decided to create a fork which allows me to only draw borders on the bottom of decorations. Its something that I'd wanted to do anyhow  (eg, just being able to either specify a single color for all four sides as is or the ability to specify a color for top, bottom, left, and right—much as we can in css); however, I think it works nicely with the rounded corners setup. Given i3 is in the state of fix bugs over introduce new features, I don't imagine that a PR which introduces the ability to more granularly config borders would be accepted; however, if people are interested, I'd be happy to work on a PR which does that properly (as opposed to my fork which currently hardcodes how to draw the borders). In either case, I thought I'd throw the idea out there in case anyone else is looking at this PR and would like a similar setup.

image

**Pull request closed without merging**
