### PR TITLE
Add RELEASE-NOTES for next release

### LINKED ISSUE #4040: Maintain release notes on next branch
Right now, release notes are written by @stapelberg whenever preparing a new release. Instead of that, I propose that we should maintain a `RELEASE-NOTES-next` file where contributors briefly explain their change, if needed.

Pros:
- Faster releases, probably doable in a couple of minutes
- We can summarize changes better when they are fresh. This will lead to higher-level changelogs.
- Users can read the changelog of the `next` branch for a peek of current changes

Cons:
- One extra thing to check & remember at each PR

TODO:
- [x] Place and initialize (with current changes) relevant file somewhere on the tree
- [x] Update contrib instructions
- [ ] Update scripts if needed
  - [ ] File must cleared at each release
- [x] Make current release notes more consistent in tree. We only have the notes from 14.1, 16.1, 18.1 right now.

### PR DESCRIPTION
**Pull request by orestisfl**
Closes #4040

### CODE REVIEW

**Review by stapelberg — APPROVED** [review]
Can you mention the autoconf change, too, before merging?

**Comment by orestisfl** [comment]
> Can you mention the autoconf change, too, before merging?

This https://github.com/i3/i3/pull/4049?

**Comment by stapelberg** [comment]
Yep

**Comment by orestisfl** [comment]
up

**Review by stapelberg — APPROVED** [review]

**Pull request merged**
