### PR TITLE
_con_move_to_con: don't change focus when moving to active workspace

### PR DESCRIPTION
**Pull request by orestisf1993**

### CODE REVIEW

**Comment by orestisf1993** [comment]
Ah this proved harder than it looked. I'll look into the failing tests.

**Comment by orestisf1993** [comment]
Not a super pretty solution but _con_move_to_con is used / con_move_to_workspace is used in a bunch of places.

**Comment by Airblader** [comment]
Looks like Travis had a hiccup there. Can you just push some change + push undoing that again so re-trigger Travis?

**Comment by orestisf1993** [comment]
up

**Pull request merged**
