### PR TITLE
Update i3-sensible-terminal

### PR DESCRIPTION
**Pull request by norrland**
Adding 'termit' to the list of terminals.

### CODE REVIEW

**Comment by Airblader** [comment]
What is "termit"? I only know "termite" and that's already in the list.

**Comment by stapelberg** [comment]
https://packages.debian.org/stretch/termit

**Comment by norrland** [comment]
https://github.com/thestinger/termite

**Comment by Airblader** [comment]
@stapelberg Shouldn't we only be appending new entries at the end? Otherwise we can break `i3-sensible-terminal` for users who have both installed.

**Comment by stapelberg** [comment]
No, people should set the `TERMINAL` environment variable or replace calls to i3-sensible-terminal with executing their favorite terminal. On distributions such as Debian, `x-terminal-emulator` takes care of user preferences, and other distributions are welcome to follow suit.

**Comment by Airblader** [comment]
Just seems like a no-brainer as it adds no complexity to avoid breakage, but I'm all for pushing users towards reasonable setups.

**Pull request merged**
