### PR TITLE
fix travis/check-spelling.pl for recent Lintian changes

### PR DESCRIPTION
**Pull request by stapelberg**

### CODE REVIEW

**Review by orestisfl — APPROVED** [review]
You can temporarily disable the pipeline and we can merge the other PR with the fix. Sucks to have two different fail reasons 😛

**Comment by orestisfl** [comment]
Or just manually merge it

**Comment by stapelberg** [comment]
I have cherry-picked your commit into this PR. Let’s see if we can get it merged easily this way :)

**Comment by stapelberg** [comment]
I’m glad I didn’t just disable the pipeline, because I had to update your fix :)

Just changing from `|` to `||` isn’t enough, because that will change the short-circuit behavior. With `|`, all expressions are run, but with `||`, evaluation will abort after the first `true` result.

**Comment by orestisfl** [comment]
Oops, you are right, should have paid more attention

Another way to work around this is to force the result into ints

**Pull request merged**
