### PR TITLE
tree_flatten: remove redundant stacked / tabbed containers

### LINKED ISSUE #3001: split + layout stacked / tabbed creates redundant containers
Output of `i3 --moreversion 2>&- || i3 --version`:

```
Binary i3 version:  4.14-128-gc08ef361 (2017-09-29, branch "next") © 2009 Michael Stapelberg and contributors
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:

https://logs.i3wm.org/logs/5637036128075776.bz2

**What I did:**

1. fresh workspace
2. open window
3. layout stacked
4. open window
5. split v
6. layout stacked
7. repeat 5-6

**What I saw:**

2017-09-30-042426_1680x1009

Repeating this too many times makes i3 unbearably slow and memory usage skyrockets.

**What I expected instead:**
Redundant stacked / tabbed containers should not be opened.

### PR DESCRIPTION
**Pull request by orestisfl**
Fixes #3001.

Before merging I'd like to:

- [ ] Run this patch for a few days on my system
- [ ] Write tests.

Submitting this PR to receive some first feedback.

### CODE REVIEW

**Comment by Airblader** [comment]
I think tests would be really good to have here. :-)

**Comment by orestisf1993** [comment]
Isn't this to be rejected according to the discussion in #3001?

**Comment by Airblader** [comment]
Yeah, that makes sense. I didn't spend much time looking at this right now because I figured tests would help clear it up. I guess we haven't actually decided on rejecting this yet either. However, I think it makes sense to close the PR for now and discuss it on the issue (where I think @stapelberg should chime in). We can reopen the PR when needed. Sound good?

**Comment by orestisf1993** [comment]
Sounds good

**Pull request closed without merging**
