### PR TITLE
 complete-run.pl: Un-set I3SOCK

### PR DESCRIPTION
**Pull request by orestisfl**
This causes test breakage when the developer/tester is running the tests in i3, as the actual active instance socket is used instead of the test instance.

Besides breaking tests, this is quite dangerous as tests like 319-gaps.t will replace the **actual** config of the user (i.e. ~/.config/i3/config) instead of the current test config.

Broken after #5987

### CODE REVIEW

**Comment by waterkip** [comment]
I would suggest setting `$ENV{I3SOCK}` to something else (or undef it) in `testcases/lib/i3test.pm.in`.

**Comment by orestisfl** [comment]
> I would suggest setting `$ENV{I3SOCK}` to something else (or undef it) in `testcases/lib/i3test.pm.in`.

No objection but that can be left as a follow up, correctness over optimization

**Comment by waterkip** [comment]
I think the testsuite (outside of the CPAN module) does something incorrect. I don't think the standalone CPAN module should cater that fix.

**Comment by orestisfl** [comment]
@waterkip I've un-set the env-var in the testsuite, should work.

**Comment by waterkip** [comment]
lgtm

**Review by stapelberg — APPROVED** [review]

**Pull request merged**
