### PR TITLE
[Adopted] Use WM_SIZE_HINTS when available to set the geometry of floating windows

### PR DESCRIPTION
**Pull request by Airblader**
This is an adopted PR from #1456 by @pronobis since he seems to have abandoned the PR. I only incorporated the review comment. Since I'm not running KDE / Plasma, I cannot test it. So someone should verify this.

### CODE REVIEW

**Comment by stapelberg** [comment]
I’m not merging code that is untested, and nobody seems to want to test it. Do you want to test it? If not, please close it and pick it up again once a user asks for this.

**Comment by Airblader** [comment]
I would test it but it seems that setting up Plasma to run with i3 is somewhat painful so I couldn't really get it to work. I'm not all too interested in spending time on something no one seems to want enough to do more than leave a comment, so I'm going to close the PR. As you said, when someone is willing to test it, we can pick it up again.

**Comment by jck** [comment]
To get plasma to run i3, all you need to do is `export KDEWM=i3` before starting kde in .xinitrc.

This patch works for me. I'm able to run plasma 5 with the default i3 config. Krunner, kickoff and other plasmoids behave well. The only problems I noticed were the splash screen and desktop background (That's not related to this fix, just wanted to put it out there).

I tested using this method: https://help.github.com/articles/checking-out-pull-requests-locally/
So, it didn't include commits made after this PR.

**Comment by Airblader** [comment]
@jck That alone didn't work for me in a VM as well as some other ways. Anyway, thanks for the feedback. 

@stapelberg Is this enough feedback for you?

**Comment by jck** [comment]
@Airblader The wallpaper covers the entire screen, that makes it look like i3 hasn't loaded.

**Comment by Airblader** [comment]
@stapelberg It's been three weeks. Is there anything else you want to wait for?

**Comment by stapelberg** [comment]
Sorry, I’m traveling since early July. I’ll get back to this when I’m back home and had a chance to test it/look at it in detail.

**Comment by Airblader** [comment]
No problem. I just brought it up because there were other merges, but they were minor. Enjoy your travels ;)

**Comment by pronobis** [comment]
So, after a long break, I finally got around to re-installing my system and i3. I did test the commit in this pull request and it works just fine. I would be happy to see it merged to next. 

Note: I had to create a new commit in my own fork for this since the branch of this PR (and the commit itself) does not seem to exist anymore in @Airblader 's fork. It might still work just fine to merge the PR though, so please ignore the "new" commit referenced above.

**Comment by pronobis** [comment]
As a side note, there are other problems with running i3 with plasma, for which I have fixes in my fork (e.g. the desktop being managed by i3). I'm happy to share those as well, although I'm not 100% sure they are of great quality.

**Comment by Airblader** [comment]
It does still exist in my repository, but you have to use my fork "i3-original", not "i3". The latter is actually i3-gaps. An unfortunate confusion resulting from the fact that i3 only moved to github not too long ago.

**Pull request merged**
