### PR TITLE
Update ewmh focused only when new focus is different

### LINKED ISSUE #3495: Windows lose their _NET_WM_STATE_FOCUSED state
## I'm submitting a…
<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Reproduction Instructions

1. Switch to empty workspace and open an app window.
   Result: the app window is focused in i3 and it is in `_NET_WM_STATE_FOCUSED` state.

2. Press `Mod1+w` to change layout.
   Result: the app window is still focused in i3 but it isn't in `_NET_WM_STATE_FOCUSED` state (but it is expected to be in this state).

I recommend to check it with GTK+ 3 app (e.g. gucharmap) since it has different appearance if it isn't in `_NET_WM_STATE_FOCUSED` state; or `xterm -T test -e "watch -n0.1 'xprop -name test | grep ^_NET_WM_STATE'"`.

Another example of losing this state: open an app window, then open and close dmenu (`Mod4+d`, `Esc`).

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.15-339-gf16afef7 (2018-10-29, branch "remotes/origin/HEAD") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.15-339-gf16afef7 (2018-10-29, branch "remotes/origin/HEAD") (pid 20374)
Loaded i3 config: /home/alice/.config/i3/config (Last modified: Sat 03 Nov 2018 01:51:15 +07, 28062 seconds ago)

The i3 binary you just called: /home/alice/dist/github.com/i3/i3/build/r/usr/local/bin/i3
The i3 binary you are running: i3
</pre>

Default config.

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): no
</pre>

### PR DESCRIPTION
**Pull request by orestisf1993**
Fixes #3495.

### CODE REVIEW

**Comment by orestisf1993** [comment]
I'll write a better test tomorrow, this one doesn't fail on next and I'll also test the closing window case.

Travis fails for an unrelated reason though (@stapelberg).

**Comment by stapelberg** [comment]
I think you’ll need to rebase your PR onto next to pick up the travis fix.

**Comment by orestisf1993** [comment]
Yes, I'll do it later after I enhance the tests.

**Comment by orestisf1993** [comment]
Up. Commands don't produce the first issue, only keybindings since they result in focus in events.

**Pull request merged**
