### PR TITLE
clear surface on x_push_node

### LINKED ISSUE #3577: Graphics artifacts with i3-wm on amdgpu
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

I am currently experiencing graphics artifacts/corruption when opening windows on i3-wm. I've asked for help on #radeon thinking this was a driver issue but MrCooper suggested this to be a bug in i3.

https://bugs.freedesktop.org/show_bug.cgi?id=105910#c10

Here's some of our conversation from today:

https://people.freedesktop.org/~cbrill/dri-log/?channel=radeon&date=2019-01-04

I am running i3wm on a Ryzen 5 2400G desktop using the integrated vega graphics. I am also using the modesetting xorg driver.

The artifacts occur when I run a program and when the program hasn't drawn anything yet, the artifacts then are gone after the program finished loading. I've seen this bug mostly with Qt applications.

My system details:
 
- Arch Linux
- mesa 18.3.1-1
- Linux 4.20.0-arch1-1-ARCH

## Expected Behavior

No image corruption/artifacts when opening new windows.

## Reproduction Instructions

Start an application on i3wm and observe corruption when the application hasn't drawn anything yet.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.16 (2018-11-04) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16 (2018-11-04) (pid 536)to abort…)
Loaded i3 config: /home/diego/.config/i3/config (Last modified: Mon 24 Dec 2018 02:33:19 AM -02, 999901 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

https://github.com/diegoviola/dotfiles/blob/master/.config/i3/config

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): No.
</pre>

### PR DESCRIPTION
**Pull request by andresilva**
Fixes #3577.

### CODE REVIEW

**Comment by andresilva** [comment]
ping

**Review by Airblader — CHANGES_REQUESTED** [review]
Thanks for the PR, and sorry for the wait for such a simple change. I think the change sounds reasonable, and we should just go ahead with it and test it. However, can you please update the release notes to add an entry for this fix? If you ping me again afterwards I'll merge it.

**Comment by andresilva** [comment]
@Airblader added a bugfix entry to the release notes.

**Review by Airblader — APPROVED** [review]

**Comment by Airblader** [comment]
Thank you!

**Pull request merged**
