### PR TITLE
nagbar: autodismiss after given seconds

### PR DESCRIPTION
**Pull request by jwdeitch**
Requires compiling with -lpthreads

### CODE REVIEW

**Comment by Airblader** [comment]
Thanks for the contribution. Can you explain what this change is needed for? The nagbar is supposed to do its title justice, so automatically closing it goes against its purpose.

**Comment by jwdeitch** [comment]
In my particular use-case, I have configured a keybinding to take a screenshot of a region on my screen and upload to S3. I wanted a way to notify me that the upload was complete and that the link was in my clipboard, without requiring my input. I can also see this being useful with emails, irc pings, etc.

**Comment by Airblader** [comment]
Out of curiosity, why not run an actual notification daemon like Dunst and using send-notify to do this? 

i3-nagbar isn't really meant for transient notifications, but rather for nagging the user that an action is required (for example, config errors).

**Comment by acrisci** [comment]
I think I agree with @Airblader here. Nagbar has a pretty limited use case within the project, primarily to notify users of configuration errors. It's not intended to be a general purpose application for notifications.

It sounds like your problem is much better solved by a real notification daemon. Lots of people like dunst but xfce also has a very nice standalone notification app. See `man notify-send` for more information.

**Comment by jwdeitch** [comment]
Makes sense. Thanks for the feedback!

**Pull request closed without merging**
