### PR TITLE
i3bar: Remove duplicate call to kick_tray_clients

### LINKED ISSUE #4159: System tray icons dissapear on reload
## I'm submitting a…

<pre>
[x] Bug

</pre>

## Current Behavior
System Tray Icons disappear on reloading. I downgraded i3 to 4.18.1 and the system tray works fine

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.18.2
</pre>

<pre>
- Linux Distribution & Version: Archlinux ( 5.4.53-1 lts)
- Are you using a compositor (e.g., xcompmgr or compton): Yes
</pre>

### LINKED ISSUE #4162: tray icon applications crash: ERROR: Error getting _XEMBED_INFO property: error_code 3
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
When starting i3, two sys tray applets are crashing. `nm-applet` and `pasystray`. The error in the i3 log is:

```
[../i3-4.18.2/../i3-4.18.2/i3bar/src/xcb.c:885] ERROR: Error getting _XEMBED_INFO property: error_code 3
/bin/sh: line 1:   823 Trace/breakpoint trap   (core dumped) nm-applet > $HOME/var/log/nm-applet.log 2>&1
/bin/sh: line 1:   826 Trace/breakpoint trap   (core dumped) pasystray --notify=all > $HOME/var/log/pasystray.log 2>&1
```

## Expected Behavior
Before upgrading to version 4.18.2 (2020-07-26), I had no problems, and the icons would show up and the applications would continue to run.

## Reproduction Instructions

I have the following in my i3 config (happens on 2 separate machines)

```
exec --no-startup-id nm-applet >$HOME/var/log/nm-applet.log 2>&1
exec --no-startup-id pasystray --notify=all >$HOME/var/log/pasystray.log 2>&1
```

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version:
Binary i3 version:  4.18.2 (2020-07-26) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.18.2 (2020-07-26) (pid 792) abort…)
Loaded i3 config: /home/brian/.config/i3/config (Last modified: Thu 30 Jul 2020 01:40:06 PM EDT, 6168 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<details><summary>Config file</summary><pre>
# Filename:         .config/i3/config-logos
# Last Modified:    2020-07-30
# vim: filetype=i3config
#
# http://i3wm.org/docs/userguide.html
# ----------------------------------------------------------------------

# Hack (undocumented feature) to make multiple monitors all one
# workspace
# fake-outputs 3840x1200+0+0

set $host logos

# change modkey to super
set $mod Mod4

# Workspace handling
# ----------------------------------------------------------------------
# Font Awesome 4.7.0 cheatsheet: https://fontawesome.com/v4.7.0/cheatsheet/

# set workspace variables and names
set $ws_term        "1: "
set $ws_browser     "2: "
set $ws_mail        "3: "
set $ws_chat        "4: "
set $workspace5     "5"
set $workspace6     "6"
set $workspace7     "7: "
set $ws_music       "8: "
set $workspace9     "9"
set $workspace10    "10"

# assign workspaces to monitors (logos-only)
workspace $ws_term      output DP1
workspace $ws_mail      output DP1
workspace $workspace5   output DP1
workspace $workspace7   output DP1
workspace $workspace9   output DP1
workspace $ws_browser   output HDMI2
workspace $ws_chat      output HDMI2
workspace $workspace6   output HDMI2
workspace $ws_music     output HDMI2
workspace $workspace10  output HDMI2

# From this point on, the config follows the user manual sections
# ----------------------------------------------------------------------

# 2.1 Opening terminals and moving around
#------------------------------------------------------------------------
bindsym $mod+Return exec termite
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# 2.2 Changing the container layout
# ----------------------------------------------------------------------
bindsym $mod+e layout toggle split
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed

# 2.3 Toggling fullscreen mode for a window
# ----------------------------------------------------------------------
bindsym $mod+f fullscreen

# 2.4 Opening other applications
# ----------------------------------------------------------------------
bindsym $mod+d exec rofi -show drun

# 2.5 Closing windows
# ----------------------------------------------------------------------
bindsym $mod+shift+q kill

# 2.6 Using workspaces
# ----------------------------------------------------------------------
bindsym $mod+1 workspace $ws_term
bindsym $mod+2 workspace $ws_browser
bindsym $mod+3 workspace $ws_mail
bindsym $mod+4 workspace $ws_chat
bindsym $mod+5 workspace $workspace5
bindsym $mod+6 workspace $workspace6
bindsym $mod+7 workspace $workspace7
bindsym $mod+8 workspace $ws_music
bindsym $mod+9 workspace $workspace9
bindsym $mod+0 workspace $workspace10

# 2.7 Moving windows to workspaces
# ----------------------------------------------------------------------
bindsym $mod+shift+1 move container to workspace $ws_term
bindsym $mod+shift+2 move container to workspace $ws_browser
bindsym $mod+shift+3 move container to workspace $ws_mail
bindsym $mod+shift+4 move container to workspace $ws_chat
bindsym $mod+shift+5 move container to workspace $workspace5
bindsym $mod+shift+6 move container to workspace $workspace6
bindsym $mod+shift+7 move container to workspace $workspace7
bindsym $mod+shift+8 move container to workspace $ws_music
bindsym $mod+shift+9 move container to workspace $workspace9
bindsym $mod+shift+0 move container to workspace $workspace10

# 2.11 Floating
# ----------------------------------------------------------------------
bindsym $mod+shift+space floating toggle

# 4.2 Fonts
# ----------------------------------------------------------------------
font pango:Sauce Code Pro 8

# 4.6 The floating modifier
# ----------------------------------------------------------------------

# use $mod + mouse left click to move floating windows
# use $mod + mouse right click to resize floating windows
floating_modifier $mod

# 4.7 Constraining floating window size
# ----------------------------------------------------------------------
floating_minimum_size 75 x 50
floating_maximum_size -1 x -1

# 4.8 Orientation for new workspaces
# ----------------------------------------------------------------------
default_orientation horizontal

# 4.9 Layout mode for new containers
# ----------------------------------------------------------------------
workspace_layout default

# 4.10 Window title alignment
# ----------------------------------------------------------------------
title_align left

# 4.11 Default border style for new windows
# ----------------------------------------------------------------------
default_border          pixel 3
default_floating_border normal

# 4.12 Hiding borders adjacent to the screen edge
# ----------------------------------------------------------------------
hide_edge_borders smart

# 4.13 Arbitrary commands for specific windows (for_window)
# ----------------------------------------------------------------------
# The new window is assigned to the workspace of the first rule that
# matches. So order rules from most-specific to least-specific.
# for_window [class="Termite" instance="termite"]                                           border pixel 0  floating disable
# for_window [class="Google-chrome" instance="mail.google.com__mail" window_role="pop-up"]  border pixel 0  floating disable
# for_window [class="Signal" instance="signal" window_role="browser-window"]                border pixel 0  floating disable
# for_window [class="^Spotify$" instance="^spotify$"]                                       border pixel 0
# for_window [class="^Galculator$" instance="^galculator$"]                                 border normal   floating enable
# for_window [class="Pinentry-gtk-2" instance="pinentry-gtk-2"]                             border normal   floating enable
# for_window [class="^Pavucontrol$" instance="^pavucontrol$"]                               border normal   floating enable
# for_window [class="^System-config-printer.py$" instance="^system-config-printer.py$"]     border normal   floating enable

# 4.17 Automatically putting clients on specific workspaces
# ----------------------------------------------------------------------
assign      [class="Google-chrome"  instance="^google-chrome$"          window_role="browser"]          $ws_browser
assign      [class="Brave-browser"  instance="^brave-browser$"          window_role="browser"]          $ws_browser
assign      [class="Signal"         instance="^signal$"                 window_role="browser-window"]   $ws_chat
assign      [class="Google-chrome"  instance="mail.google.com__mail"    window_role="pop-up"]           $ws_mail

# spotify needs to use for_window
for_window  [class="^Spotify$"      instance="spotify"] move to workspace $ws_music

# 4.18 Automatically starting applications on i3 startup
# ----------------------------------------------------------------------
exec --no-startup-id i3-msg 'workspace $ws_term; exec termite --exec="tmux -2u new-session -s home -c $HOME -A"; workspace $ws_term'
exec --no-startup-id picom >$HOME/var/log/picom.log 2>&1
exec --no-startup-id dunst -print >$HOME/var/log/dunst.log 2>&1
exec --no-startup-id nm-applet >$HOME/var/log/nm-applet.log 2>&1
exec --no-startup-id pasystray --notify=all >$HOME/var/log/pasystray.log 2>&1
exec --no-startup-id $XDG_CONFIG_HOME/redshift/launch.sh
exec --no-startup-id xautolock -time 10 -locker "$XDG_CONFIG_HOME/i3/lock.sh"
exec --no-startup-id clipster --daemon

# 4.22 Focus follows mouse
# ----------------------------------------------------------------------
focus_follows_mouse yes

# 4.23 Mouse warping
# ----------------------------------------------------------------------
mouse_warping none

# 5 Configuring i3bar
# ----------------------------------------------------------------------
bar {

    # 5.2 Statusline command
    # ------------------------------------------------------------------
    status_command py3status --dbus-notify --log-file ~/var/log/py3status.log

    # 5.3 Display mode
    # ------------------------------------------------------------------
    mode dock
    hidden_state show
    modifier none

    # 5.6 Position
    # ------------------------------------------------------------------
    position top

    # 5.7 Output
    # ------------------------------------------------------------------
    # output HDMI2

    # 5.8 Tray output
    # ------------------------------------------------------------------
    # tray_output primary

    # 5.10 Font
    # ------------------------------------------------------------------
    font pango:DejaVu Sans Mono, FontAwesome5Free, FontAwesome5Brands 10

    # 5.16 Colors
    # ------------------------------------------------------------------
    colors {
        background          #222222
        statusline          #dddddd
        separator           #666666

        # <colorclass> <border> <background> <text>
        focused_workspace   #0088CC #0088CC #ffffff
        active_workspace    #333333 #333333 #ffffff
        inactive_workspace  #333333 #333333 #888888
        urgent_workspace    #2f343a #900000 #ffffff
    }

    # 5.9 Tray padding
    # ------------------------------------------------------------------
    tray_padding 2
}

# 6.19 Reloading/Restarting/Exiting
# ----------------------------------------------------------------------
bindsym $mod+shift+r    restart
bindsym $mod+shift+c    reload
bindsym $mod+shift+e    exec $XDG_CONFIG_HOME/i3/exit-menu.sh
bindsym $mod+Escape     exec --no-startup-id $XDG_CONFIG_HOME/i3/lock.sh

# Navigation
# ----------------------------------------------------------------------

# Volume control
# ----------------------------------------------------------------------
bindsym XF86AudioLowerVolume exec /usr/sbin/pactl set-sink-volume @DEFAULT_SINK@ -5%
bindsym XF86AudioRaiseVolume exec /usr/sbin/pactl set-sink-volume @DEFAULT_SINK@ +5%
bindsym XF86AudioMute exec /usr/sbin/pactl set-sink-mute @DEFAULT_SINK@ toggle

# Move windows
bindsym $mod+shift+h move left
bindsym $mod+shift+j move down
bindsym $mod+shift+k move up
bindsym $mod+shift+l move right

# Split in horizontal orientation (bar key)
bindsym $mod+shift+backslash split h

# Split in vertical orientation (underscore key)
bindsym $mod+shift+minus split v

# Application-specific keyboard shortcuts
# ----------------------------------------------------------------------
# shortcut to clipster's selection widget (primary)
bindsym $mod+c exec clipster --primary --select

# Pop-up windows
# ----------------------------------------------------------------------
popup_during_fullscreen leave_fullscreen
# for_window [window_role="GtkFileChooserDialog"] \
#     enable border normal \
#     floating enable \
#     resize 300 300

# no_focus [window_role="pop-up"]

# Application key bindings
# ----------------------------------------------------------------------

# Resizing
# ----------------------------------------------------------------------
bindsym $mod+r mode "resize"
mode "resize" {
    bindsym h   resize shrink   width   5 px or 5 ppt
    bindsym j   resize shrink   height  5 px or 5 ppt
    bindsym k   resize grow     height  5 px or 5 ppt
    bindsym l   resize grow     width   5 px or 5 ppt

    # Same bindings, but for the arrow keys
    bindsym Left    resize shrink   width   5 px or 5 ppt
    bindsym Down    resize shrink   height  5 px or 5 ppt
    bindsym Up      resize grow     height  5 px or 5 ppt
    bindsym Right   resize grow     width   5 px or 5 ppt

    # Back to normal: Enter or Escape
    bindsym Return mode "default"
    bindsym Escape mode "default"
}

# Colorscheme (dark green)
# Source: http://dotshare.it/dots/1473/
# ----------------------------------------------------------------------

# Hybrid colors
set $black      #0f1419
set $white      #e6e1cf
set $gray       #CCCCCC
set $darkgray   #666666
set $green      #3a5336
set $blue       #4D73AA
set $purple     #8473A7
set $red        #ff3333
set $orange     #f29718
set $cyan       #3d7982
set $dark       #404152

# class                 border  background  text    indicator
client.focused          $black  $green      #ffffff $black
client.focused_inactive $dark   $dark       $white  $dark
client.unfocused        $dark   $dark       $white  $dark
client.urgent           $red    $red        $white  $red
</pre></details>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5712597579988992.bz2
</pre>

<pre>
- Linux Distribution & Version: arch, Linux logos 5.7.10-arch1-1 #1 SMP PREEMPT Wed, 22 Jul 2020 19:57:42 +0000 x86_64 GNU/Linux
- Are you using a compositor (e.g., xcompmgr or compton): yes, picom
</pre>

### PR DESCRIPTION
**Pull request by orestisfl**
Fixes #4159
Fixes #4162

### CODE REVIEW

**Review by HaoZeke — APPROVED** [review]

**Comment by somercet** [comment]
I don't know much about i3, but I hit this bug when I upgraded on Arch:

[2020-07-30T18:14:19-0400] [ALPM] upgraded i3-wm (4.18.1-1 -> 4.18.2-1)

For me, this bug triggers whenever I run a video game, Urban Terror. Xpad dumps core, and Hexchat closes when I run the game. Those are the only two apps showing in the systray.

The above patch does not fix this issue for me. I recompiled i3-wm using:

https://www.archlinux.org/packages/community/x86_64/i3-wm/

Thank you.

**Comment by nylocx** [comment]
I also applied this patch to the i3-gaps package and still have the bug if I quit and restart i3bar.

**Comment by orestisfl** [comment]
This patch should be applied to the next branch, not the stable branch. For stable, apply https://github.com/i3/i3/commit/838b600fead202416013db5c1b57f7031f06bed6

**Comment by btmcg** [comment]
I created issue https://github.com/i3/i3/issues/4162 and applied this patch to the `next` branch. After running the new binary, the issue continues to happen in exactly the same way. Anything in particular you'd like me to provide?

**Comment by btmcg** [comment]
Here is a stacktrace from the nm-applet coredump:

```
#0  0x00007f8246469314 in g_log_writer_default () from /usr/lib/libglib-2.0.so.0
[Current thread is 1 (Thread 0x7f8244ed4280 (LWP 314159))]
(gdb) bt
#0  0x00007f8246469314 in g_log_writer_default () at /usr/lib/libglib-2.0.so.0
#1  0x00007f8246466a29 in g_log_structured_array () at /usr/lib/libglib-2.0.so.0
#2  0x00007f8246466f81 in g_log_structured_standard () at /usr/lib/libglib-2.0.so.0
#3  0x00007f8246983c11 in  () at /usr/lib/libgdk-3.so.0
#4  0x00007f8246990e95 in  () at /usr/lib/libgdk-3.so.0
#5  0x00007f824600f83b in _XError () at /usr/lib/libX11.so.6
#6  0x00007f824600c5e8 in  () at /usr/lib/libX11.so.6
#7  0x00007f824600c685 in  () at /usr/lib/libX11.so.6
#8  0x00007f824600cfea in _XEventsQueued () at /usr/lib/libX11.so.6
#9  0x00007f8245ffe992 in XPending () at /usr/lib/libX11.so.6
#10 0x00007f824698b331 in  () at /usr/lib/libgdk-3.so.0
#11 0x00007f824645ef80 in g_main_context_prepare () at /usr/lib/libglib-2.0.so.0
#12 0x00007f82464ae086 in  () at /usr/lib/libglib-2.0.so.0
#13 0x00007f824645f221 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#14 0x00007f8246659c9e in g_application_run () at /usr/lib/libgio-2.0.so.0
#15 0x00005620603781a9 in  ()
#16 0x00007f8247152002 in __libc_start_main () at /usr/lib/libc.so.6
#17 0x00005620603782fe in  ()
```

For the record, the last 8 frames of the pasystray coredump are exactly the same.

**Comment by btmcg** [comment]
Ok, sorry for the spam.

It was my mistake. Once I put the version of i3bar I built ahead of the system-installed one in my PATH, this patch worked. Both applets stay running and show up in the system tray without a problem. So, for my issue https://github.com/i3/i3/issues/4162, at least, I can confirm that this PR fixes it.

Thanks!

**Review by stapelberg — APPROVED** [review]

**Pull request merged**
