### PR TITLE
[wip] Tiling drag

### PR DESCRIPTION
**Pull request by acrisci**
A continuation of #2178 

TODO

- [ ] Support stacks and tabs
- [x] Don't always create new splits
- [ ] Drag onto the root window
- [x] Drop indicator for inner/outer regions
- [x] Implement outer region drop
- [ ] Initiate tiling drag from titlebar
- [ ] Emit move event properly on tiling drop
- [ ] Refactor `insert_con_into()` into con.c
- [ ] Configure color of drop indicator
- [ ] Bug: i3 crashes if a window closes while the dragging is indicating to drop it onto that window.
- [ ] Tests

### CODE REVIEW

**Comment by Airblader** [comment]
Glad to see this being continued. I think this is a really cool feature to have in i3.

FYI @MForster

**Comment by MForster** [comment]
Awesome! 👍

**Comment by acrisci** [comment]
There is definitely an interesting UX problem here. I'll share my initial thoughts. Any input is appreciated.

I think we should define two separate drop regions. There will be an "inner region" and an "outer region" on the edges.

Which region you drop in will determine whether it will do a split, or insert it as a sibling within the parent container.

These will then be divided into four quadrants. The quadrant will determine the direction of the move.

```
         +------------------------------------------------+
         |XX                                             X|
         |  X           SIBLING ABOVE                  XX |
         |   X+--------------------------------------+X   |
         |    |                                      |    |
         |    |               SPLIT ABOVE            |    |
         |    |                                      |    |
         |    |                  +                   |    |
         |    |                  |                   |    |
         |    |                  |                   |    |
         |    |                  |                   |    |
SIBLING LEFT  |SPLIT LEFT        |        SPLIT RIGHT|   SIBLING RIGHT
         |    |          +----------------+          |    |
         |    |                  |                   |    |
         |    |                  |                   |    |
         |    |                  |                   |    |
         |    |                  |                   |    |
         |    |                  +                   |    |
         |    |                                      |    |
         |    |               SPLIT BELOW            |    |
         |    |                                      |    |
         |    +--------------------------------------+    |
         |XX X         SIBLING BELOW                  X X |
         +-X----------------------------------------------+

```

This is just the first thing I thought of. Does that make sense?

**Comment by Airblader** [comment]
Yeah, that makes sense to me. I wonder whether we could use regions to switch the container to stacked or tabbed as well. Might be too complex a mental model, though.

**Comment by acrisci** [comment]
The outer/inner indicator is now implemented but not the actual movement.

**Comment by acrisci** [comment]
I think mouse features are probably less useful when you need to press a key to initiate them. I'd like to initiate a drag with the mouse only.

What if dragging from the title bar initiated the tiling drag (in addition to the modifier)? That would be consistent with normal gui conventions where dragging a title bar is a movement action.

**Comment by Airblader** [comment]
SGTM.

**Comment by acrisci** [comment]
The outer region drop behavior is ready to test.

**Comment by Airblader** [comment]
I think one general issue with the dragging feature is that percentages aren't kept. It's a pretty tough issue that I've tackled in my swap command PR (which is still open). I'm not sure we really do need to »fix«/support it for the dragging feature.

Also, i3 crashes if I move the mouse over i3bar while dragging a window.

**Comment by Airblader** [comment]
Please disregard what I said about percentages. Not only don't we need to fix anything here, but it just doesn't even make sense since in general dragging windows changes the tree.

**Comment by acrisci** [comment]
@Airblader can you think of what needs to be done besides my TODOs on the OP? Do we need tests?

**Comment by Airblader** [comment]
@acrisci I'll have to take a look at the change itself (which I didn't yet). In general tests are always a good thing to have. As it stands this is probably a little tricky to test. I wonder whether we should also provide this feature as a command along the lines of

````
drag [window|container] [to] sibling|split left|right|top|bottom for <con_id>
````

which would have the added extra benefit of making it testable without simulating mouse behavior.

Apart from that I've played around with it for a few minutes now. Except for that one crash it seems to work fine even in the few edge cases I could immediately think of. But it did bring me back to my previous idea about drop locations to create tabbed and stacked containers (but perhaps let's just keep this as a future idea for now).

One minor thing coming to mind would be to allow separate customization of the drop indicator via its own `color.drop_indicator` directive (with the fallback to the focused window or something).

**Comment by Airblader** [comment]
i3 crashes if a window closes while the dragging is indicating to drop it onto that window.

**Comment by acrisci** [comment]
I think we can use XTEST (or xdotool) to simulate a mouse click then warp the pointer and release the mouse. That's kind of involved, but this feature is complicated enough that maybe that is worth it.

The `drag` command won't cover the case that you just mentioned here.

I think the outer region should be increased as well, but I'm not sure exactly how large it should be.

**Comment by Airblader** [comment]
> The drag command won't cover the case that you just mentioned here or the other crash with the bar either.

I don't really strongly advocate implementing the command. Using XTEST is perfectly fine with me as well. :-)

> I think the outer region should be increased as well, but I'm not sure exactly how large it should be.

I agree that they seemed a little small. We don't have to get it perfect right away. Let's play with it a little.

**Comment by Airblader** [comment]
@acrisci Do you plan on working on this still?

**Comment by acrisci** [comment]
I think I just have too much going on right now to work on this, but I wish someone would continue this work because I think it has the potential to be a good feature.

**Comment by Airblader** [comment]
Thanks. I do agree as well that this would be really cool and hope someone will continue. I also agree on not having enough time at the moment. :-) I'll close this for now since we have the open issue #2643 for it.

**Comment by orestisf1993** [comment]
Watchers of this PR: I opened a continuation in #3085.

**Pull request closed without merging**
