### PR TITLE
Use the DPI setting within the i3bar

### PR DESCRIPTION
**Pull request by mihaicmn**

### CODE REVIEW

**Comment by Airblader** [comment]
I like the change, but please make sure the formatting is correct. :-)

**Comment by mihaicmn** [comment]
Is there any procedure that has to be followed to format the code?

**Comment by Airblader** [comment]
You just run `clang-format` on the code, i.e.,

```
clang-format -i $(find . -name "*.[ch]" | tr '\n' ' ')
```

**Comment by Airblader** [comment]
The changes look good to me, but can you please squash them into a single commit so we can keep the git log clean?

**Pull request merged**
