### PR TITLE
AnyEvent::I3: rip out taint mode compatibility

### PR DESCRIPTION
**Pull request by stapelberg**
I suspect nobody actually uses Perl’s taint mode with AnyEvent::I3.

See https://github.com/i3/i3/pull/5987 for discussion.

### CODE REVIEW

**Comment by stapelberg** [comment]
@waterkip Can you verify that AnyEvent::I3 still works as expected for you with this PR applied? Thanks.

**Comment by waterkip** [comment]
It works as expected, my script keeps working.

**Comment by stapelberg** [comment]
@orestisfl Could you approve this change when you have a second please? :)

**Review by orestisfl — APPROVED** [review]
Sorry, this slipped through

**Pull request merged**
