### PR TITLE
Check if subscribe event type is supported in AnyEvent::I3

### PR DESCRIPTION
**Pull request by waterkip**
Add simple `if exists' construct in the subscribe function. This prevents a somewhat cryptic warnings such as these:

Use of uninitialized value $type in hash element at /usr/share/perl5/AnyEvent/I3.pm line 309.

We still warn the user, but it is much clearer as to what the cause is.

It now shows something like this:

Could not subscribe to event type 'foo'. Supported events are _error barconfig_update binding mode output shutdown tick window workspace

### CODE REVIEW

**Comment by spwhitton** [comment]
Thanks, this prevents one having to dive into the code to know why you can't, e.g., subscribe to ticks on the version of this lib in Debian.

**Comment by waterkip** [comment]
> Thanks, this prevents one having to dive into the code to know why you can't, e.g., subscribe to ticks on the version of this lib in Debian.

That was actually the reason why I added this :)

**Comment by spwhitton** [comment]
> > Thanks, this prevents one having to dive into the code to know why you can't, e.g., subscribe to ticks on the version of this lib in Debian.
> 
> That was actually the reason why I added this :)

Quite the coincidence that two of us were trying to do this today :)

**Comment by waterkip** [comment]
> > > Thanks, this prevents one having to dive into the code to know why you can't, e.g., subscribe to ticks on the version of this lib in Debian.
> > 
> > 
> > That was actually the reason why I added this :)
> 
> Quite the coincidence that two of us were trying to do this today :)

Indeed. I also filed a bug report at Debian btw, see bts 1068616.

**Comment by spwhitton** [comment]
> > > > Thanks, this prevents one having to dive into the code to know why you can't, e.g., subscribe to ticks on the version of this lib in Debian.
> > > 
> > > 
> > > That was actually the reason why I added this :)
> > 
> > 
> > Quite the coincidence that two of us were trying to do this today :)
> 
> Indeed. I also filed a bug report at Debian btw, see bts 1068616.

FTFY

**Review by stapelberg — APPROVED** [review]

**Pull request merged**
