### PR TITLE
Include what you use

### PR DESCRIPTION
**Pull request by zybreak**
Simply a code refactorization, instead of importing an "all.h" header file in most c-files which contains all project header-files, we now only include those header files needed for the specific c-file in question.

The benefit is a better overview of whats being used and where as well as easier to spot unused header-files

### CODE REVIEW

**Comment by orestisfl** [comment]
Thank you for this PR.

Related issue: #4022

I don't think it's worth it to begin practicing "header discipline". Unused header files are not a big problems and seeing where each file gets its definitions from doesn't seem that useful right now.

@stapelberg WDYT?

**Comment by stapelberg** [comment]
Yeah, it looks like the time savings are very small:

Without this PR:
```
ninja  15,73s user 2,51s system 1282% cpu 1,422 total
ninja  15,87s user 2,26s system 1265% cpu 1,433 total
ninja  15,81s user 2,51s system 1291% cpu 1,419 total
```

With this PR:
```
ninja  15,23s user 2,53s system 1263% cpu 1,406 total
ninja  15,28s user 2,53s system 1255% cpu 1,418 total
ninja  15,62s user 2,30s system 1274% cpu 1,406 total
```

Does include-what-you-use (the tool) work without problems on the i3 code base and with little setup? If so, we could consider merging this. If no, it’s probably not worth the hassle.

**Comment by orestisfl** [comment]
I would argue that maintaining the extra dev/CI dependency and having to manually include files are not really worth it.

**Comment by zybreak** [comment]
I haven't looked into whether the include-what-you-use tool will work or not, but I could do that if you think that would be of any benefit.

My hope was that this would bring clarity to the code, as I was struggling a bit to get a good overview with the all.h header.

I hope you can evaluate the suggestion again from a code clarity aspect. If you feel this brings little or no added clarity and just a hassle of writing a lot more imports, I would argue that writing imports is not a big deal. And new developers can get a pretty good idea of whats in use by looking at them.

If you have an editor with good features, it will show you any imports not needed (thus removing the need to run the tool seperately) 

Anyways, enough ranting.

**Comment by stapelberg** [comment]
> I haven't looked into whether the include-what-you-use tool will work or not, but I could do that if you think that would be of any benefit.

I think if we find that the IWYU tool is easy to set up and works well with the i3 code base, that would be the only case in which I could be convinced to accept this PR. 

> I hope you can evaluate the suggestion again from a code clarity aspect. If you feel this brings little or no added clarity and just a hassle of writing a lot more imports, I would argue that writing imports is not a big deal.

I agree that listing headers explicitly is good from a code clarity perspective. But at the same time, having to manually modify headers when moving code around is such a hassle, it overweighs the benefit of clarity.

**Comment by Airblader** [comment]
Having to change includes in i3 is something that occurs very, very rarely these days anyway. 

Except for enums and data types, most functions also follow the convention of being prefixed by their file name, which makes it pretty clear where they're coming from.

**Comment by orestisfl** [comment]
I feel the consensus here is to not merge this. Feel free to reopen otherwise.

**Pull request closed without merging**
