### PR TITLE
Temporary fix for #2276

### PR DESCRIPTION
**Pull request by layus**
@Airblader  It would be really nice to have this merged. I know it is not a proper fix, but at least we would not experience repeated segfaults in the meantime. #2276 has been open for a full year. How long will it take to receive a proper fix ?

### CODE REVIEW

**Comment by Airblader** [comment]
Thanks for your contribution.

I'm going to decline this because I'd like to avoid merging workarounds. They tend to make something better in the short run, but overall it hides an issue that isn't understood and might only lead to making it even harder to figure out the problem.

> How long will it take to receive a proper fix ?

As soon as somebody spent the time to figure out the root cause and comes up with the fix for it (which doesn't necessarily have to be the same person). Everybody is welcome to do so. :-)

That said, if the issue is a big pain for you and you don't want to invest the time, you can run your patch locally. I hope you understand why I don't want to merge it, though.

**Comment by layus** [comment]
Yep, I understand. I can indeed patch locally, but I find this quite deceptive for other users who may encounter the same issue.

**Comment by Airblader** [comment]
Once you have the workaround in upstream, nobody wants to spend time on the issue ever again, though. :-)

**Comment by layus** [comment]
Unless the issue comes out again. Otherwise the workaround is a real fix, even if no-one knows why ;-). *Half kidding here*

**Comment by Airblader** [comment]
Once you stop understanding the software you deliver, you're in big trouble. :-)

**Pull request closed without merging**
