### PR TITLE
fix i3-nagbar invocation

### PR DESCRIPTION
**Pull request by dcoppa**
i3-nagbar already launch the command inside a terminal, thus the "pageraction" string in commands.c is wrong. While here, also fix the manpage example.

### CODE REVIEW

**Comment by Airblader** [comment]
i3-nagbar launches it with /bin/sh, not $EDITOR, though, doesn't it?

**Comment by dcoppa** [comment]
What about "i3-sensible-editor ~/.config/i3/config" then?

**Comment by stapelberg** [comment]
Do you realize the code is commented out? :) I think it might be better to finally remove that code.

**Comment by dcoppa** [comment]
omg! I badly need some days off, it seems... facepalm

The manpage fix is still valid though ;)

**Comment by stapelberg** [comment]
Can you update the pull request to either not touch the commented-out code or remove it please?

**Comment by dcoppa** [comment]
I've removed the commented-out code.

**Comment by stapelberg** [comment]
Thanks! One more thing before I can merge this: can you please squash your commits? Currently, the pull request contains 5 commits, and we really need just 2 in our history (remove dead code, update manpage).

**Pull request closed without merging**
