### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by george124816**

### CODE REVIEW

**Review by Airblader — APPROVED** [review]
Thanks, much appreciated! :+1:

**Comment by Airblader** [comment]
@stapelberg Are you aware of that [CI failure](https://github.com/i3/i3/runs/6668063196?check_suite_focus=true)?

**Comment by stapelberg** [comment]
> @stapelberg Are you aware of that [CI failure](https://github.com/i3/i3/runs/6668063196?check_suite_focus=true)?

Thanks for the pointer. I sent https://github.com/i3/i3/pull/4992 to fix the issue

**Comment by Airblader** [comment]
@george124816 Do you mind rebasing your branch to update it and fix the CI? Thank you!

**Comment by Airblader** [comment]
You actually merged into your branch instead of rebasing. This would leave the history messy. Can you please rebase it so that only your commit is contained in the branch?

**Comment by george124816** [comment]
@Airblader done

**Pull request merged**
