### PR TITLE
Don't raise floating windows when focused because of focus_follows_mouse

### LINKED ISSUE #2990: Don't move floating windows to the top with focus_follows_mouse
Output of `i3 --moreversion 2>&- || i3 --version`:
```
Binary i3 version:  4.14.1 (2017-09-24) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.14.1 (2017-09-24) (pid 1411)abort…)
Loaded i3 config: /home/eyenseo/.config/i3/config (Last modified: Mon 25 Sep 2017 15:07:42 CEST, 114 seconds ago)
The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
```

URL to a logfile as per https://i3wm.org/docs/debugging.html:
Not needed.

**What I did:**

[Video](https://vimeo.com/235356494)

Had a small floating window over a big floating window, moved the mouse to copy text and then moved the mouse back to the small window.

**What I saw:**
After the mouse was back over the small window I saw the big window as the focus was moved to it and thus it was moved to the top.

**What I expected instead:**
The small window as  *I* did not change the focus. 

This should not be the default behavior - I had similar issues where the mouse mealy touched the big window because I was overshooting the small one, it is inconvenient enough that I use `focus_follows_mouse no` at the moment.

### PR DESCRIPTION
**Pull request by orestisfl**
Fixes #2990.

I am not too happy with the `_con_focus` name, I'd love to hear better suggestions for the change. If the code logic is ok and once we conclude on a name I'll properly reformat con.{c,h} (spacing, comments etc).

### CODE REVIEW

**Comment by stapelberg** [comment]
Sorry for letting this linger for so long.

I think what we should do instead of introducing an option to con_focus is to pull the raise logic into a separate function and call it where appropriate — i.e. whenever we programmatically change focus, not as a reaction to a FocusIn event.

**Comment by orestisf1993** [comment]
Shouldn't we keep FocusIn events? This will reintroduce #2572.

**Comment by stapelberg** [comment]
I thought #2572 is about reacting to a menu-triggered raise, e.g. via the Window menu in GIMP. That would trigger a programmatic change, not a FocusIn. Am I misunderstanding that issue?

**Comment by orestisf1993** [comment]
Hmm, I am not sure actually. I just checked by making the `con_focus` call in `handle_focus_in` not raise floating windows. Now, with `xdotool windowfocus ...` floating windows are not raised to the top. Isn't this a case that we want them to be raised to the top?

**Comment by stapelberg** [comment]
No: xdotool windowfocus sends SetInputFocus.

The way to programmatically request focus from the window manager is via a _NET_ACTIVE_WINDOW ClientMessage sent to the root window. xdotool implements that as xdotool windowactivate.

**Comment by orestisf1993** [comment]
Yes you are correct. But I think FocusIn events are not the cause of #2990, MotionNotify and/or EnterNotify are.

**Comment by stapelberg** [comment]
We’d definitely get EnterNotify, but I think FocusIn events are also generated. It could be that we don’t receive them because we temporarily change the event mask when sending SetInputFocus — I’d have to look that up.

**Comment by orestisf1993** [comment]
I think this comment explains it:

https://github.com/i3/i3/blob/4f751610c2a51fb35755db87fafee8598d6d7bd3/src/handlers.c#L1202-L1208

**Comment by jolange** [comment]
What's the status here? I'm very interested in a solution to #2990, because it makes the current i3 version unusable for me.

**Comment by stapelberg** [comment]
> I think what we should do instead of introducing an option to con_focus is to pull the raise logic into a separate function and call it where appropriate — i.e. whenever we programmatically change focus, not as a reaction to a FocusIn event.

That comment is still not addressed AFAICT.

**Comment by orestisf1993** [comment]
> I think what we should do instead of introducing an option to con_focus is to pull the raise logic into a separate function and call it where appropriate — i.e. whenever we programmatically change focus, not as a reaction to a FocusIn event.

Doesn't this mean that we would have to make changes in most parts of the code where `con_focus` is called?

**Comment by stapelberg** [comment]
Yes, we’ll need to identify where the raise function should be called (as opposed to just the focus function).

**Comment by orestisf1993** [comment]
My problem with this approach is that we'll have to review each call of `con_focus` (about 50 of them) and see if it makes sense to add extra code to raise a possible floating container. Except for the 2 or 3 calls that cause #2990 I think that the other `con_focus` calls that also raise are either harmless (exclusively for tiling windows) or reasonable defaults until they cause a problem.

I propose to:
1. Make `_con_focus` a static
2. Keep `con_focus` as is in this PR
3. Add `con_focus_background` (or whatever appropriate name) that just calls `_con_focus(con, false);`
Use that when we explicitly don't want to raise floating containers

**Comment by orestisf1993** [comment]
I pushed my proposal from https://github.com/i3/i3/pull/2998#issuecomment-349166626

**Comment by stapelberg** [comment]
Thanks for your continued work on this PR.

> My problem with this approach is that we'll have to review each call of con_focus (about 50 of them) and see if it makes sense to add extra code to raise a possible floating container. Except for the 2 or 3 calls that cause #2990 I think that the other con_focus calls that also raise are either harmless (exclusively for tiling windows) or reasonable defaults until they cause a problem.

I don’t follow. You already did the review of each call. You identified the ones which should not raise. Why don’t you use string-replace on all con_focus calls to make them con_focus; con_raise;, then remove the raise from the 3 calls where we don’t want to raise? :)

**Comment by orestisf1993** [comment]
My arguments against your approach are:

It increases boilerplate code for almost all calls of `con_focus`.

It can be misleading: there might be some places where we know that we are focusing a tiling container (eg in `con_swap`). Combining this with a raise call could confuse the reader.

Your approach will also need to introduce a new function since `floating_raise_con` already assumes floating containers. This new function will also need to use recursion (`con_inside_floating`) to identify the correct floating container.

**Comment by stapelberg** [comment]
> It increases boilerplate code for almost all calls of con_focus.

I’m willing to live with that if it means avoiding options in con_focus.

> It can be misleading: there might be some places where we know that we are focusing a tiling container (eg in con_swap). Combining this with a raise call could confuse the reader.

Let’s not add raise calls in places where we know we operate on tiling containers, then. Also, let’s add a comment to the raise function documenting that it’s a no-op on tiling containers and safe to remove in that case.

**Comment by orestisf1993** [comment]
> I’m willing to live with that if it means avoiding options in con_focus.

What's so bad with the option in `_con_focus`?

**Comment by stapelberg** [comment]
It makes a very core piece of the code much harder to follow.

Function parameters which change the function behavior are the most prevalent anti-pattern in the i3 code base by far, so I’m really against introducing any more. Past refactorings and bug fixes have shown that these are very tricky to deal with.

A better alternative is to have well-scoped functionality in small functions, which is what I’m advocating for here.

**Comment by orestisf1993** [comment]
I think it's not such a big issue here since the caller doesn't have to figure out the parameters like with `        con_move_to_workspace(con, ws, true, false, false)`. I also don't agree with a solution that introduces more code duplication, another prevalent problem in the i3 code base.

Would you agree to replace `con_focus` with:
```
void con_activate(Con *con){
    con_focus(con);
    con_raise(con); /* the new raise function */
}
```
?

This way we are making "focusing" and "activating" a window separate concepts, like in xdotool. You can hover over a window to "focus" it but you need to click it in order to "activate" it.

We could also move some `workspace_show` and urgency code inside `con_activate`.

**Comment by stapelberg** [comment]
Sounds good, let’s give that a shot.

**Comment by orestisf1993** [comment]
An alternative to prevent the project-wide rename and the inconsistency between the `focus` command and the "activate" concept I talked about would be to:

```
void con_focus(Con *con){
    con_focus_background(con);   /* or whatever name */
    con_raise(con);
}
```

would you prefer that?

**Comment by stapelberg** [comment]
> would you prefer that?

No, I think I prefer the activate concept actually :)

**Comment by orestisf1993** [comment]
I've pushed the rename. Let's check the changes to see if it doesn't make sense in some places.

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
Looks good to me. We can fix calls one-by-one whenever we discover one where the window should not be raised.

**Comment by Sonique** [comment]
So how can I use it in my i3wm configuration? Pretty annoying issue :)

**Comment by Airblader** [comment]
@Sonique There's no need for configuration. If you run a version compiled with this patch it should work.

**Comment by languitar** [comment]
Is there any plan when a new release will be made including this fix? The current behavior drives me crazy...

**Comment by Airblader** [comment]
We're aiming to release over the next few days.

**Pull request merged**
