### PR TITLE
Fix name of mcedit

### PR DESCRIPTION
**Pull request by jwilk**
It's `mcedit`, not `mc-edit`.

### CODE REVIEW

**Comment by stapelberg** [comment]
Could it be that some distributions ship it as mc-edit? Should we have both here?

**Comment by jwilk** [comment]
I doubt `mc-edit` is a thing. There's exactly one hit on [DCS](https://codesearch.debian.net/search?q=%5Cbmc-edit%5Cb) (i3 itself), no hits on [RPM search](http://rpm.pbone.net/); I couldn't find anything relevant on Google either.

@hboetes, it was apparently you who added `mc-edit` to the list of editors (ac3541c28ce44fb9ce992c605d1f6ca00557fd8e).
Was it a typo for `mcedit` or is there actually a distro that ships it under this name?

**Comment by hboetes** [comment]
I can't look it up right now, but the intention was the editor that is
provided by the midnight commander package.

Am 31.10.2016 12:06 schrieb "Jakub Wilk" <notifications@github.com>:

**Comment by Airblader** [comment]
@jwilk @hboetes What's the status here?

**Comment by hboetes** [comment]
Right, the proper name is mcedit indeed.

**Comment by Airblader** [comment]
@stapelberg Then this should be good to go.

**Pull request merged**
