### PR TITLE
i3bar stuff

### PR DESCRIPTION
**Pull request by shdown**
(See the commit messages.)

### CODE REVIEW

**Comment by teto** [comment]
Are click on workspace buttons handled properly or are the click events sent to the bar even if the status line is shortened ? I had this problem with overlapping status lines that clicking on workspace buttons would get ignored.

**Comment by shdown** [comment]
> Are click on workspace buttons handled properly

No :(

I'll see what can be done by me.

**Comment by shdown** [comment]
OK, I pushed the fix that works for me.

**Comment by Airblader** [comment]
This looks good to me. I was just getting started on implementing `short_text`, but I will wait to see whether this is merged, to avoid conflicts.

**Comment by Airblader** [comment]
Man, I just merged this into my fork to make merging i3 into it easier once this is merged. That was quite a task. :smile:

**Pull request closed without merging**
