### PR TITLE
workspace_move_to_output: fix ws creation

### LINKED ISSUE #3745: "workspace move to output" creates ws on original output based on name instead of number
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

Let's say we work with 2 monitors, with only 2 empty workspaces.

When the ws is only a number:
```i3
workspace 1
move workspace to output right
```
- moves **ws 1** on right output
- creates **ws 11** on left output

When the ws is a number and a name:
```i3
workspace 1:foo
move workspace to output right
```
- moves **ws 1:foo** on right output
- creates **ws 1** on left output

## Expected Behavior

```move workspace to output``` should create a new workspace on the original output based on the existing workspaces *number*, not *name*.

## Reproduction Instructions

See **Current Behavior**

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 
Binary i3 version:  4.16.1-195-g90385edc (2019-07-21, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1-195-g90385edc (2019-07-21, branch "gaps-next") (pid 940)
Loaded i3 config: /home/antoine/.config/i3/config (Last modified: Thu 25 Jul 2019 11:43:56 AM PDT, 1068 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3
</pre>

<pre>
The default i3 config reproduces the bug.
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Debian_GNULinux_10_buster
- Are you using a compositor (e.g., xcompmgr or compton): yes, compton
</pre>

### PR DESCRIPTION
**Pull request by antoinemadec**
Fixes #3745

### CODE REVIEW

**Comment by Airblader** [comment]
@stapelberg Are there plans for a next release? I would merge this, I think, but not "right before" a release since I think it makes sense to see if this is more helpful or more inconvenient for users.

**Comment by stapelberg** [comment]
> @stapelberg Are there plans for a next release? I would merge this, I think, but not "right before" a release since I think it makes sense to see if this is more helpful or more inconvenient for users.

Yeah, I can prepare a new release next week. It’s time :)

**Comment by orestisfl** [comment]
A test failed here

**Comment by stapelberg** [comment]
> A test failed here

@antoinemadec Looks like your change breaks test testcases/t/304-ipc-workspace-init.t. Could you take a look when you get a chance please?

**Comment by antoinemadec** [comment]
@stapelberg OK.
I followed the doc to run this test, but I encountered the following error:

> Can't locate X11/XCB.pm in @INC (you may need to install the X11::XCB module)

I am not familiar with Perl, could you please let me know how to install this module?

**Comment by stapelberg** [comment]
> I am not familiar with Perl, could you please let me know how to install this module?

Please see https://i3wm.org/docs/testsuite.html#_installing_the_dependencies

**Comment by antoinemadec** [comment]
That's what I did.
It installed some Perl module, but im still missing one module.

**Comment by antoinemadec** [comment]
> > I am not familiar with Perl, could you please let me know how to install this module?
> 
> Please see https://i3wm.org/docs/testsuite.html#_installing_the_dependencies

After looking at the build log, the error was caused by the absence of the xcb-proto package.
`sudo apt install xcb-proto`
Maybe we could add this in the testsuite doc?

**Comment by antoinemadec** [comment]
@stapelberg I just spent roughly 5 hours trying to debug the failing test using this command:
`sudo ./complete-run.pl --parallel=1 --keep-xserver-output ../../testcases/t/304-ipc-workspace-init.t`

I tried **printf** among other things and I still don't have a clear understanding of the state of the windows between commands.

I also tried to use **x11vnc** with ```sleep(5)``` between commands in order to see what Xephyr was doing.
Unfortunately I only saw black and white shapes moving...

My question is the following: is there a graphical (or clear debug prints) that can show what is the sate of the windows in between commands?

Thanks,
Antoine

**Comment by orestisfl** [comment]
To debug the test I would recommend to copy the test's condig (add a `bar {` and maybe some keybinds to be easier to use) and use Xephyr + gdb to launch i3

**Comment by antoinemadec** [comment]
@stapelberg @Airblader @orestisfl I just fixed the issue:
```PASS: testcases/complete-run.pl```

However Travis CI had an issue yesterday, could you please re-trigger a build?

**Comment by stapelberg** [comment]
> I just fixed the issue:

Glad to hear it, and sorry for not being able to come up with better pointers for how to debug the test. Which strategy worked best in the end? What was the issue?

We need to make the commit description more descriptive: currently it doesn’t convey the changes in behavior to the end user. How about something like “move workspace to output: don’t create duplicatively numbered workspaces”?

Also, please include the “fixes #3745” line in your commit message.

Lastly, please interactively rebase your git commits into just one commit—we’d like to have a clean git history.

**Comment by antoinemadec** [comment]
> Glad to hear it, and sorry for not being able to come up with better pointers for how to debug the test. Which strategy worked best in the end?

No problem, I used debug prints like these:
```perl
my $ptr = get_workspace_names();
foreach $ws_name (@$ptr) {
    $ws_output = get_output_for_workspace($ws_name);
    print "DEBUG: (ws_name, output) = ($ws_name, $ws_output)\n";
}
print("DEBUG: ws_focused=", focused_ws(), "\n");
```
The testsuite was actually harder to understand than the source code itself :smile: 

> What was the issue?

When creating a new ws, we check if assignment ws are available.
To test whether an assignment ws is attached, I was using this:
```c
get_existing_workspace_by_num(ws_name_to_number(assignment->name)) != NULL
```
Which is always true for _named_ ws.
I now use ```test get_existing_workspace_by_name``` for _named_ ws, ```get_existing_workspace_by_num``` otherwise.

Sorry about the dirty commits, it's all clean now.
Thanks a lot for maintaining this amazing project :+1: 

Cheers,
Antoine

**Comment by stapelberg** [comment]
Thanks!

**Pull request merged**
