### PR TITLE
Makefile.am: Use BUILT_SOURCES for GENERATED headers

### LINKED ISSUE #3670: Makefile try to compile i3-config-wizard before i3-config-parser.stamp on many threads building
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

A failure occurred in build
```
 GEN      man/i3-config-wizard.xml
  GEN      man/i3-migrate-config-to-v4.xml
  GEN      man/i3-sensible-editor.xml
  GEN      man/i3-sensible-pager.xml
  GEN      man/i3-sensible-terminal.xml
  GEN      man/i3-dump-log.xml
  GEN      man/i3-dmenu-desktop.1
  GEN      man/i3-save-tree.1
  GEN      docs/debugging.html
  GEN      docs/lib-i3test.html
  GEN      docs/lib-i3test-test.html
  GEN      docs/hacking-howto.html
  GEN      docs/userguide.html
../../i3/i3-config-wizard/main.c:109:10: fatal error: GENERATED_config_enums.h: No such file or directory
 #include "GENERATED_config_enums.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2774: i3-config-wizard/i3_config_wizard-main.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/build/i3-gaps-next-git/src/i3/build'
make: *** [Makefile:1332: all] Error 2
 
```
When building on many threads concurrently, the generated Makefile may try to compile i3-config-wizard before i3-config-parser.stamp and result an error where GCC cannot find the to-be-generated header file. This error happens at a low possibility
## Expected Behavior

Successfully make without error.
## Reproduction Instructions

```
autoreconf --force --install
../configure  --prefix=/usr  --sysconfdir=/etc  --disable-sanitizers 
make CPPFLAGS+="-U_FORTIFY_SOURCE" -j$(nproc)
```
In my environment $(nproc) is 24.
## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.16.1-152-g767a6a52 (2019-03-28, branch "gaps-next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1-152-g767a6a52 (2019-03-28, branch "gaps-next") (pid 544)
Loaded i3 config: /home/marvelous/.config/i3/config (Last modified: Fri 29 Mar 2019 04:25:31 PM HKT, 8376 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>
</pre>

<pre>
Logfile URL:
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

### PR DESCRIPTION
**Pull request by orestisfl**
See commit message

Fixes #3670

CC FYI:
@stapelberg 
@Hi-Angel (#4020 should be a different issue)

### CODE REVIEW

**Review by stapelberg — APPROVED** [review]
Nice find! Thank you.

Can you add a quick mention of https://www.gnu.org/software/automake/manual/html_node/Sources.html to the commit message please?

**Comment by stapelberg** [comment]
Can you rebase to pick up https://github.com/i3/i3/pull/4065 please?

**Comment by orestisfl** [comment]
> Nice find! Thank you.
> 
> Can you add a quick mention of https://www.gnu.org/software/automake/manual/html_node/Sources.html to the commit message please?

The commit message is pretty verbose, what are you missing?

**Comment by stapelberg** [comment]
Ah, that link is already in the full commit message. Sorry, I didn’t see that because the GitHub UI doesn’t show it at the top of the diff, and I always go straight to the diff. Maybe I should change that habit :)

**Pull request merged**
