### PR TITLE
Remove the A_TO_OUTPUT option

### PR DESCRIPTION
**Pull request by Airblader**

### CODE REVIEW

**Comment by Airblader** [comment]
@stapelberg I believe that the tests should be successful and that this is an unrelated timing issue. The test is also successful locally for me.

**Comment by acrisci** [comment]
:+1:

**Comment by stapelberg** [comment]
I think c35b3160f6e0c07cfbaa3a09baed6ebde48c8417 addresses the test failure. As you can see in the details, one run succeeded and one didn’t.

**Comment by stapelberg** [comment]
Thanks for the cleanup!

**Pull request merged**
