### PR TITLE
degendered terms

### PR DESCRIPTION
**Pull request by garbados**
changed gendered terms like "he" and "his" to "they" and "their"

### CODE REVIEW

**Comment by garbados** [comment]
for [this line](https://github.com/i3/i3/blob/next/src/randr.c#L659) i wasn't sure if "his" referred to a male user or some lowercase acronym, so i left it alone pending confirmation.

**Comment by garbados** [comment]
hmm, but "he or she" excludes people who aren't he or she, ex: nonbinary folk. they doesn't.

**Comment by garbados** [comment]
also, um

https://en.wikipedia.org/wiki/Singular_they#Usage_guidance_in_English_grammars

> According to A Comprehensive Grammar of the English Language (1985):
>
> > The pronoun they is commonly used as a 3rd person singular pronoun that is neutral between masculine and feminine. . . . At one time restricted to informal usage. it is now increasingly accepted in formal usage [...]

**Comment by acrisci** [comment]
I really don't think "nonbinary folk" will feel not included by everyday normal English.

I can list several style guides that advise against it from the same article. The fact that it is controversial at all is a reason to avoid it when you can.

There is a difference between someone saying it is "increasingly accepted in formal usage" and putting a ban on gendered pronouns and mandating the exclusive usage of singular they like you want to do. Can you find any reputable source that says gendered pronouns are bad style?

**Comment by garbados** [comment]
scare quotes around nonbinary? i'm sorry, i don't want to make this thread unprofessional. i'll message you on irc.

**Comment by Airblader** [comment]
I'm strongly in favor of the singular they. As far as I know it's not academically accepted, but other than that fine. This isn't an academic document. 

It's much nicer to read than the terrible "he or she"  every single time a pronoun is used.

**Comment by acrisci** [comment]
I thought our documentation language was already gender inclusive, but @garbados has told me that they do not feel included so I retract my strong objection to this.

**Comment by stapelberg** [comment]
Thanks. I find it interesting how there are both the generic masculine and generic feminine form sprinkled across comments and docs.

With regards to the line you weren’t sure about: replacing “his” by “output” would be my suggestion.

**Comment by garbados** [comment]
cool! i'll make another pr for the `his -> output` change :)

**Pull request merged**
