### PR TITLE
Extended GET_WORKSPACE response with workspace ID.

### LINKED ISSUE #3891: Add workspace ID in IPC response to GET_WORKSPACES request.
## I'm submitting a…
<pre>
[ ] Bug
[x] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
At the moment, the **only** link between WORKSPACE event response (i3 node) and GET_WORKSPACES response is the workspace name.
It feels unnatural(and inefficient) to use a workspace name as ID to link stored data from GET_WORKSPACES response and incoming WORKSPACE events.
Also, all of this relies on uniqueness of workspace names, which might change in the future.

## Desired Behavior
The WORKSPACE event provides the client with i3's node data which already contains ID of the node.
It would be very convenient if GET_WORKSPACES would also provide ID for each workspace node.

## Environment
Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: 4.17.1 (2019-08-30)
</pre>

### PR DESCRIPTION
**Pull request by Iskustvo**
Closes #3891.

### CODE REVIEW

**Comment by Iskustvo** [comment]
@Airblader, looks like the tests were failing because they used i3bar for parsing of the GET_WORKSPACES response. Therefore, I have also updated the i3bar's parser to address the newly added ID and that fixed the tests.

**Comment by Airblader** [comment]
Looks good, thanks! Could you please squash the commits? Then we're all set.

**Comment by Iskustvo** [comment]
Done!

**Comment by Airblader** [comment]
Thanks!

**Pull request merged**
