### PR TITLE
docs/hacking-howto: Promote "Using git / sending patches" section

### LINKED ISSUE #2907: Please add README or INSTALL file
There is currently no documentation in the project tree root on how to build i3. Please add a file describing the correct / supported way to do so.

If the documentation is elsewhere, please add a README file linking or directing readers to said location.

A README (or README.md) or INSTALL file is an established convention among open-source projects; it would be good if i3 followed suit.

Additionally, a README.md (or README) file will be automatically rendered by GitHub [on the project's main GitHub page](https://github.com/i3/i3), so it would be a good place to link to the project website and online documentation there.

### PR DESCRIPTION
**Pull request by CyberShadow**
Fixes #2907.

### CODE REVIEW

**Comment by Airblader** [comment]
Can you squash those commits, please?

**Comment by CyberShadow** [comment]
Are you sure? I did this change as one commit first, then I redid it as separate commits so it's possible to actually read the diff.

You can also squash it while merging in GitHub's UI, no?

**Comment by Airblader** [comment]
Squashing shouldn't affect the overall diff. Since you only moved a few sections we don't need more than one commit for that.

**Comment by CyberShadow** [comment]
> Squashing shouldn't affect the overall diff.

That's why there are multiple commits. It's not possible to discern the smaller changes from the overall diff (or that of a single squashed commit).

> Since you only moved a few sections we don't need more than one commit for that.

Not really. Sorry, have you read the commit messages? Or do you mean that the changes that weren't just literally moving a single block of text around are too minor to be in their own commits?

**Comment by Airblader** [comment]
Ah, I actually misses that you made changes other than moving the section. You're completely right in this case, of course.

**Pull request merged**
