### PR TITLE
Allow --whole-window right after 'bindsym' within binding modes

### LINKED ISSUE #1629: Mouse binding doesn't respond in mode
in `~/.i3/config`:

    mode "test" {
       bindsym Escape mode "default"
       bindsym --whole-window button3 exec xterm
    }
    bindsym $mod+t mode "test"

1. enter "test" mode
2. right click

expected: xterm opens
actual: nothing happens

### PR DESCRIPTION
**Pull request by Airblader**
fixes #1629

### CODE REVIEW

**Comment by stapelberg** [comment]
Can you add a test for this in t/187-commands-parser.t please?

**Comment by Airblader** [comment]
@stapelberg commands-parser != config-parser. I'll set up a new test class for config parsing.

**Comment by stapelberg** [comment]
Why not t/201-config-parser.t then?

**Comment by Airblader** [comment]
Because I didn't see that yet. :)

**Pull request merged**
