### PR TITLE
Check cairo status in draw_util_surface_free()

### PR DESCRIPTION
**Pull request by psychon**
Since my #4379 is not going to work, I thought that one could at least improve the logging a bit, hopefully making debugging easier in the future.

While looking at this code, I found a minor memory leak that I am also fixing in this PR.

### CODE REVIEW

**Comment by psychon** [comment]
Sigh, and something in the tests hangs again... I'll investigate.

**Review by orestisfl — CHANGES_REQUESTED** [review]
Was the hang caused by the segfault situation you mention in the commit? In that case I'd squash the faulty commit (also the clang-format one).

**Comment by psychon** [comment]
> Was the hang caused by the segfault situation you mention in the commit? 

Uhm. My guess would be "yes", but it has been a quarter year, so I don't remember for sure. At least I vaguely remember being annoyed that I had some problem with crashes and the test suite and that it was quite hard to get `gdb` in the game. But I don't remember any details. 

>  In that case I'd squash the faulty commit

Done. This PR now only has two commits.

**Review by orestisfl — APPROVED** [review]
Thanks!

**Pull request merged**
