### PR TITLE
 Reduce repetition in cmd_move_con_to_workspace* 

### PR DESCRIPTION
**Pull request by orestisf1993**

### CODE REVIEW

**Comment by Airblader** [comment]
I get the reasoning for the change, but I'm not actually sure I favor it. It somewhat outsources the handling of matches in a less transparent way such that I'm not sure the couple of (repeated) lines saved is worth the indirection of the extra call here.

**Comment by orestisf1993** [comment]
IMO It's not only about the saved lines, it is made easily clear for the reader (without having to compare each function) that in the end, all `cmd_move_con_to_workspace`* do the same thing after they've acquired the target workspace.

**Comment by Airblader** [comment]
I think my argument at the moment would be that as a reader, I would see

    cmd_move_con_to_workspace(ws);

and wonder: *which con?* just to be even further surprised that it's (potentially) more than one container. Admittedly, giving it a different name might resolve that issue.

**Comment by orestisf1993** [comment]
Yeah the name is bad in retrospect. I'll find a better name.

**Comment by orestisf1993** [comment]
- `move_matches_to_workspace`
- `move_matching_windows_to_workspace`
- `move_current_matches_to_workspace`

?

**Comment by Airblader** [comment]
The first one sounds reasonable to me.

**Comment by orestisf1993** [comment]
Up

**Comment by Airblader** [comment]
Thanks!

**Pull request merged**
