### PR TITLE
 Fix aspect ratio bugs

### PR DESCRIPTION
**Pull request by orestisf1993**

### CODE REVIEW

**Comment by orestisf1993** [comment]
I think the failed tests are related to https://github.com/stapelberg/X11-XCB/commit/1777f2e64fd5995fdc381c6c9118077684a179c3

**Comment by orestisf1993** [comment]
Pretty sure X11::XCB still sends junk:
```
#   Failed test 'Window width is 100px'
#   at /usr/src/i3/build/../../i3/testcases/t/133-size-hints.t line 98.
#          got: '28016'
#     expected: '100'
```

Anything we need to do to update the module for travis?

**Comment by orestisf1993** [comment]
Travis now passed

**Comment by Airblader** [comment]
@orestisf1993 Can you rebase to resolve the conflicts? Thanks!

**Comment by orestisf1993** [comment]
up

**Pull request merged**
