### PR TITLE
Add an i3bar flag: --verbose

### PR DESCRIPTION
**Pull request by hwangcc23**
Fix the issue #3220. (https://github.com/i3/i3/issues/3220)

### CODE REVIEW

**Review by Airblader — CHANGES_REQUESTED** [review]

**Comment by hwangcc23** [comment]
Up

**Comment by orestisf1993** [comment]
We should also update the docs: https://github.com/i3/i3/blob/b68816423599037788dc719db287d131fde16896/docs/debugging#L161

We could also modify https://github.com/i3/i3/blob/b68816423599037788dc719db287d131fde16896/src/main.c#L952 to use -V whenever verbose is configured since i3bar's output is included in stderr when you start i3. It won't show up in the logs though.

**Comment by hwangcc23** [comment]
Up

**Review by Airblader — APPROVED** [review]

**Comment by Airblader** [comment]
Thanks!

**Pull request merged**
