### PR TITLE
Add 'tray_output primary' to the default config

### PR DESCRIPTION
**Pull request by Airblader**
relates to #1855

### CODE REVIEW

**Comment by stapelberg** [comment]
You’ll also need to update i3.config, I think.

**Comment by Airblader** [comment]
`i3.config` is only used for the initial startup, no? So it's a config the user usually wouldn't (shouldn't) edit and since it only has one bar block, there's no risk. But sure, I can put it there, too, if you want.

**Comment by stapelberg** [comment]
I think your rationale is sound, but also it’s better to keep the two files in sync, just to make the mental model of dealing with the two files simpler.

**Comment by Airblader** [comment]
Agreed. :)

**Pull request merged**
