### PR TITLE
Move content for non-existing output containers

### LINKED ISSUE #2276: Crash at startup with multiple monitors.
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12-17-g84c39a1 (2016-03-30, branch "next") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-17-g84c39a1 (2016-03-30, branch "next") (pid 989)
Loaded i3 config: /home/gmaudoux/.i3/config (Last modified: mer 30 mar 2016 16:16:31 CEST, 648 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html: 

http://logs.i3wm.org/logs/5718016125829120.bz2

**What I did:**

Boot and exec `startx`.

**What I saw:**

i3 crashed, the small "i3 crashed" popup appearing, but with no text, just a black box.

**What I expected instead:**

Hmm... i3 starting normally :-).

**Extra info:**

My laptop is docked an plugged to an external monitor.
To manage docking and external monitors/projectors, i use autorandr, which is called automatically when drm events are noticed. This is done by my monitormonitors script.

My feeling is that i3 crashes because my postswitch script (see below) tries to send messages to i3 just when i3 is comping with the new monitor layout notified by xrandr.

Note that autorandr is always called once to check the disposition at the begining:

```
#!/usr/bin/env python

import functools
import os.path
import pyudev
import subprocess
from pprint import pprint
from threading import Timer


def main():
    BASE_PATH = os.path.abspath(os.path.dirname(__file__))
    path = functools.partial(os.path.join, BASE_PATH)
    call = lambda x, *args: subprocess.call([x] + list(args))
    autorandr = lambda: call('/usr/bin/autorandr', '-c', '--default', 'presentation')

    context = pyudev.Context()
    monitor = pyudev.Monitor.from_netlink(context)
    monitor.filter_by(subsystem='drm')
    monitor.start()

    timer = Timer(0.5, autorandr)
    timer.start()

    for device in iter(monitor.poll, None):
        pprint(device)
        pprint(device.attributes)
        # I can add more logic here, to run only certain kinds of devices are plugged.

        # This ensures that we fire only one call to autorandr for multiple events occuring within some interval.
        timer.cancel()
        timer.join()
        timer = Timer(0.5, autorandr)
        timer.start()


if __name__ == '__main__':
    main()
```

Calling autorandr modifies the displays layout, just like calling xrandr directly with predefined options.
It also calls a custom hook (called postswitch) to move the workspaces to the right displays/monitors:

```
#!/bin/bash -x

config="$1"

primary="eDP1"
secondary="eDP1"

case "$config" in
    docked)
        primary="DP1-1"
        secondary="eDP1"
        ;;
    pr*)
        secondary="DP1-3"
        ;;
esac

move_workspace () {
    workspace="$1"
    output="$2"

    sed -i "/workspace $workspace output/ c \\workspace $workspace output $output" $HOME/.i3/config

    # is this needed ? yes !
    i3-msg workspace "$workspace"
    i3-msg move workspace to output "$output"
    i3-msg workspace 1
}
export -f move_workspace

# worspace 0 is on secondary screen
move_workspace 0 "$secondary"
# all other workspaces are on the primary display
# this is just a 'for i in 1 2 ... 10' loop ;)
parallel -kj1 move_workspace "{}" "$primary" ::: $(seq 1 10)

# got to sane default after moving everything
i3-msg workspace 1

# Is reload sufficient to remap workspaces ? Yes
# ! Neither reload nor restart do change the worspace location.
# ! Reload does not create missing (i3)bars.
#i3-msg reload
i3-msg restart
```

Here is my .xinitrc, just in case:

```
#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

# Make sure this is before the 'exec' command or it won't be sourced.
[ -f /etc/xprofile ] && source /etc/xprofile
[ -f ~/.xprofile ] && source ~/.xprofile

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xrdb -query > ~/xrdb_dump
[ -f ~/.Xresources ] && xrdb -global ~/.Xresources
if [ -d ~/.Xresources.d ]; then
  for f in ~/.Xresources.d/*; do
    [ -f "$f" ] && xrdb -global -merge "$f"
  done
  unset f
fi

xsetroot -solid '#fdf6e3'

#/home/layus/bin/blackout
sleep 1
exec i3 -d all -V >> ~/.i3/i3log 2>&1
```

I tried with the current i3 version in ArchLinux, then tried a build from the "next" branch, same issue.

Another small annoyance: When typing "r" (restart), firefox still runs but no window are visible, no window is capured by the (re)loaded layout either.

### LINKED ISSUE #2459: assert(result != NULL) in con_get_output() fails during/after undock
Output of `i3 --moreversion 2>&- || i3 --version`:

~  i3 --moreversion 2>&- || i3 --version
Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12-105-g555f458 (2016-09-12, branch "next") (pid 10664)
Loaded i3 config: /home/corni/.i3/config (Last modified: Sun 28 Aug 2016 03:55:27 PM CEST, 1736688 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: /home/corni/build/i3/i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:
bzip2 -c | curl --data-binary @- http://logs.i3wm.org

**What I did:**

Undock the laptop during suspend, then un-suspend. The docked laptop has two monitors connected, the undocked laptop just its internal display.

Instead I got the following backtrace in gdb:
img_20160917_181809
(i.e. assert(result != NULL); failed in con_get_output() in src/con.c line 365).

**What I saw:**

I3 crashed.

### LINKED ISSUE #2936: Workspaces are not moved and disapper when switching from single to multi monitor setup
Output of `i3 --moreversion 2>&- || i3 --version`:

> zeltak@zlap:~|⇒  i3 --moreversion 2>&- || i3 --version                                                          
> Binary i3 version:  4.14 (2017-09-04) © 2009 Michael Stapelberg and contributors                                
> Running i3 version: 4.14 (2017-09-04) (pid 1015)o abort…)                                                       
> Loaded i3 config: /home/zeltak/.i3/config (Last modified: Tue 12 Sep 2017 09:50:24 AM IDT, 10211 seconds ago)   
> The i3 binary you just called: /usr/bin/i3                                                                      
> The i3 binary you are running: i3  

- using Arch linux with up to date updates. 
- current i3 config: 
https://paste.xinu.at/9bqshU/

- current g.card info:
https://paste.xinu.at/kJC/

- link to similar looking issue:
https://github.com/i3/i3/issues/2201

URL to a logfile as per http://i3wm.org/docs/debugging.html:

 http://logs.i3wm.org/logs/5765486922956800.bz2

**What I did:**

when using i3 with multi monitors some work spaces just disappear when moving from the single initial login present monitor (laptop) to a multi screen setup.
in short: login to laptop with i3. all defined monitors are available. Then switch via a xrander script to a multi monitor setup:

````
#!/bin/sh
xrandr --output eDP-1 --off --output DP-2 --off --output DP-1 --off --output HDMI-1 --off --output DP-1-3 --off --output DP-1-2 --primary --mode 3440x1440 --pos 0x0 --rotate normal --output DP-1-1 --mode 2560x1440 --pos 3440x0 --rotate left & i3-msg restart
````
now ie workspace 2 is gone

**What I saw:**
workspace '2' disappeared , i cant use bind or `i3-msg workspace 2` to get to work space 2. i can see it present in rofi but its impossible to get to it through i3. 
also if i change an app to 'float' i can see the apps on work space '2' behind.

**What I expected instead:**
workspace 2 should not disappear

### LINKED ISSUE #3764: Crash on restart
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

After changing screen layout with autorandr or arandr, a i3-msg restart or bindsym ... restart will permanently crash i3. Backtrace says 'No stack.' 

## Expected Behavior

i3 restarts

## Reproduction Instructions

1. Connect to DisplayLink dock
2. `autorandr --force` to create two-screen layout
3. `i3-msg restart`

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
i3 version: Binary i3 version:  4.17-5-g3b88e41d (2019-08-08, branch "next") © 2009 Michael Stapelberg and contributors
(Getting version from running i3, press ctrl-c to abort…)
Running i3 version: 4.17-5-g3b88e41d (2019-08-08, branch "next") (pid 15890)
Loaded i3 config: /home/zach/.config/i3/config (Last modified: Wed 03 Apr 2019 01:29:49 AM MDT, 11376730 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

[My config](http://ix.io/1Rt1)

[Logfile](https://logs.i3wm.org/logs/5744766046175232.bz2)

<pre>
- Linux Distribution & Version: Arch w/ kernel version 5.2.8
- Are you using a compositor (e.g., xcompmgr or compton): maybe compton but I think it's off
</pre>

### LINKED ISSUE #3765: running i3-msg restart and using the restart keybind afterwards leads to crash of i3
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior
i3 crashes.

## Expected Behavior
i3 shouldn't crash. Bug doesn't arise with i3 4.16.1.

## Reproduction Instructions
Add "i3-msg restart" into i3 config or initiate it manually inside a terminal. Then use the keybinding to restart i3. 

## Environment
Binary i3 version:  4.17 (04.08.2019) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.17 (04.08.2019) (pid 14188) abort…)
Loaded i3 config: /home/midnight/.config/i3/config (Last modified: Mo 12 Aug 2019 23:51:04 CEST, 6520 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

<pre>
</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5638105096781824.bz2
</pre>

<pre>
- Linux Distribution & Version: Arch Linux
- Are you using a compositor (e.g., xcompmgr or compton): compton (definitely unrelated though)
</pre>

### LINKED ISSUE #3766: i3 does not adjust workspaces when switching from multi-monitor to single monitor setup in case "xrandr" command is followed by "restart" in same the bindsym
## I'm submitting a…

<pre>
[x] Bug
[ ] Feature Request
[ ] Documentation Request
[ ] Other (Please describe in detail)
</pre>

## Current Behavior

1. I trigger a bindsym that executes an xrandr command to display workspaces on my laptop and and external monitor connected to HDMI. find below the relevant line in `~/.config/i3/config`. note the `xrandr` command is followed by a `restart` command:

`bindsym $mod+control+2 exec xrandr --output DP-2-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2-2 --off --output DP-2-3 --off --output eDP-1 --mode 1366x768 --pos 232x1080 --rotate normal --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off, restart`

2. I open a couple of workspaces on my external monitor

3. I trigger another bindsym that executes an xrandr command to only use my laptop screen and stop the output the the external monitor. find below the respective line from the config file:

`bindsym $mod+control+1 exec xrandr --output DP-2-1 --off --output DP-2-2 --off --output DP-2-3 --off --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off, restart`

4. result:
the external monitor went off successfully, however the workspaces that were on the external monitor did not jump over to my laptop screen but simply dissapeared. when I tried to switch to these "lost" workspaces nothing happened, they simply seem to be disappeared.
when triggering the bindsym from 1) the "lost" workspaces appear on the external monitor again, and everything works fine.

6. note:
after removing `, restart` from the two bindsym lines in the config file and restarting i3, this issue cannot be reproduced and feature runs as expected. even if I manually trigger a restart via `$mod+Shift+r` right after the xrandr bindsym the issue cannot be reproduced. reproduction is only possible when `xrandr` is followed by `, restart` in the same bindsym

This seems to be the same / similar issue as described in a previous bug:
https://github.com/i3/i3/pull/2337
https://github.com/i3/i3/issues/2326

## Expected Behavior

when switching off the external monitor the workspaces on it should jump over to the laptop screen.

## Reproduction Instructions

see above.

## Environment

Output of `i3 --moreversion 2>&-`:
<pre>
Binary i3 version:  4.16.1 (2019-01-27) © 2009 Michael Stapelberg and contributors
Running i3 version: 4.16.1 (2019-01-27) (pid 1330)abort…)
Loaded i3 config: /home/marjan/.config/i3/config (Last modified: Di 13 Aug 2019 01:11:53 CEST, 392 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

</pre>

<pre>

# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see https://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
font pango:monospace 8

# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
#font pango:DejaVu Sans Mono 8

# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec i3-sensible-terminal

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run
# There also is the (new) i3-dmenu-desktop which only displays applications
# shipping a .desktop file. It is a wrapper around dmenu, so you need that
# installed.
# bindsym $mod+d exec --no-startup-id i3-dmenu-desktop

# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+odiaeresis focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+odiaeresis move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3
bindsym $mod+4 workspace $ws4
bindsym $mod+5 workspace $ws5
bindsym $mod+6 workspace $ws6
bindsym $mod+7 workspace $ws7
bindsym $mod+8 workspace $ws8
bindsym $mod+9 workspace $ws9
bindsym $mod+0 workspace $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3
bindsym $mod+Shift+4 move container to workspace $ws4
bindsym $mod+Shift+5 move container to workspace $ws5
bindsym $mod+Shift+6 move container to workspace $ws6
bindsym $mod+Shift+7 move container to workspace $ws7
bindsym $mod+Shift+8 move container to workspace $ws8
bindsym $mod+Shift+9 move container to workspace $ws9
bindsym $mod+Shift+0 move container to workspace $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym odiaeresis resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape or $mod+r
        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "resize"

#xrandr command to enable laptop screen only
bindsym $mod+control+1 exec xrandr --output DP-2-1 --off --output DP-2-2 --off --output DP-2-3 --off --output eDP-1 --primary --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off, restart

#xrandr command to enable laptop and external HDMI monitor
bindsym $mod+control+2 exec xrandr --output DP-2-1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP-2-2 --off --output DP-2-3 --off --output eDP-1 --mode 1366x768 --pos 232x1080 --rotate normal --output HDMI-2 --off --output HDMI-1 --off --output DP-2 --off --output DP-1 --off, restart

# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}

</pre>

<pre>
Logfile URL: https://logs.i3wm.org/logs/5682028552912896.bz2
</pre>

<pre>
- Linux Distribution & Version:
  Operating System: Ubuntu 18.04.2 LTS
   Kernel: Linux 4.15.0-55-generic
   Architecture: x86-64

- Are you using a compositor (e.g., xcompmgr or compton):
</pre>

### PR DESCRIPTION
**Pull request by orestisfl**
Probably fixes various related issues:
Closes #2276
Closes #2459
Closes #2936
Closes #3766

Tested using
`bindsym $mod+Shift+i exec xrandr --output DVI-D-0 --mode 1920x1080 --pos 0x0 --rotate normal --output DVI-I-1 --off, restart`

The core issue here is that the JSON read during a restart might contain invalid outputs when the new process is done reading it.

### CODE REVIEW

**Comment by orestisfl** [comment]
I won't be available to test this for some days. @mdnghtman, @3ach, @markbil can you verify if this fixes your issues?

**Comment by orestisfl** [comment]
I am actually not sure how the above works. We specify `get_active = true` in `xcb_randr_get_monitors`. So we should never receive an output that has been disabled but was present in the layout file.

**Comment by markbil** [comment]
> I won't be available to test this for some days. @mdnghtman, @3ach, @markbil can you verify if this fixes your issues?

@orestisfl I'd be very happy to test, though I am relatively new to linux and i3 so I am still struggling to understand a few (general) things first: I have installed i3 via apt package manager, and that's the version I am using at the moment. However, if I wanted to test your fix I guess I would need to clone i3 from github and pull your fix and then build i3 from source? how do I then run i3 from this build / where is it installed? would that not conflict with my previously installed i3 version from apt? (or do I need to remove that one first?) how would I restore my current setup after testing?
I understand those are not bug related and rather general questions, so sorry for posting this here but I'd appreciate any tips or relevant reading material to get me started. thank you!

**Comment by Iskustvo** [comment]
@markbil, This is how I've tested `i3` before, core developers might have better way...

1) Download the github repo.
It is easiest to download this `randr` branch used for pull request directly from @orestisfl.
`git clone https://github.com/orestisfl/i3.git --branch randr --single-branch`
This will download `i3` directory with current code from the branch `randr` in your current directory.

2) [Build](https://i3wm.org/docs/hacking-howto.html#_building_i3) the source code locally - Won't interact with system package that you already have.
```
cd i3
autoreconf -fi
mkdir -p build && cd build
../configure
make -j8
```
If you did this correctly, you are now inside `build` directory and there is `i3` executable with changes from this pull request.

3) Move to another virtual terminal.
Since `i3` needs `X11` display to work, and you are most likely already using current virtual terminal(display) for `i3` from system, you can't just start new instance over the existing one.
The way I work around this is to switch to another virtual terminal by pressing **Ctrl + Alt + F2**.
This will leave everything you have opened on current virtual terminal(tty1) and move you to second virtual terminal(tty2). Don't freak out, you will only have ugly terminal, without any GUI.
(When you boot your PC, your desktop starts like this as well, it just runs a few commands on top of it to bring you GUI)
**If at any point you need to go back to your original desktop(tty1), just press Ctrl + Alt + F1.
Some distros might actually use other tty for default one, but you can easily find it by trying out Ctrl + Alt + F1, Ctrl + Alt + F2 and so on.**

4) Run locally built `i3` on second virtual terminal.
Now that you are on another virtual desktop, you can tell `X11` to start rendering your new `i3` there.
`xinit [path_to_your_locally_built_i3] &> /dev/null -- :2`
If you get error that `xinit` is unknown command, download appropriate package for your distro which has it.

5) Enjoy this Linux tour and test what you wanted :D 
After last command, you should be in your locally built `i3` and can start testing what you wanted.

There are certainly other ways to use locally built `i3` instead of one on the system, but I feel like there is way bigger chance to screw your local setup while modifying things that you don't fully understand. By doing it this way, you don't change what will be started when your computer starts, you don't delete/replace system version of the package, you are simply starting another instance of locally built `i3` in another clean environment. If anything strange happens, you can always just restart PC and it will start like it always has.
**Note that even if you are on another virtual desktop, you will still be logged in as same user and will access same files in your system. So any file/directory changes that you make will stay.**

**Comment by mdnghtman** [comment]
After following the instructions by Iskustvo, the problem sadly persists.

**Comment by orestisfl** [comment]
Can you please paste the output from `i3 --version` to verify you are
running the correct version?

**Comment by mdnghtman** [comment]
i3 version 4.13-982-g73c3491b (2019-08-13, branch "randr") © 2009 Michael Stapelberg and contributors

**Comment by orestisfl** [comment]
Can you please also upload the output of `i3 --moreversion` and `i3-msg -t
get_tree` after the bug appears?

**Comment by DictumMortuum** [comment]
I was about to open a feature request for this, as I need the content shifted when at work, unplugging from the docking station to go to a meeting happens almost every day.

I'll try to test it later.

**Comment by orestisfl** [comment]
Hey, @stapelberg maybe you want to quickly review this as well. Not for the bugfix release but in order to include this on the next release.

**Pull request merged**
