### PR TITLE
Bugfix: allow exec command to properly handle quoted ';' and ','

### PR DESCRIPTION
**Pull request by kneitinger**
Fixes bug [#2122](https://github.com/i3/i3/issues/2122), "Comma enclosed in quotes".

All tests pass.

### CODE REVIEW

**Comment by Airblader** [comment]
Cool, thank you. Can you please add a line to the commit message saying "fixes #2122"?

Also, all tests passing is great, but not enough since they didn't catch this bug. Can you add a new test case that makes sure this keeps working in the future?

**Comment by kneitinger** [comment]
I certainly can, but it may take a day or so.  The Travis CI build failed, did I introduce something that breaks the build?

**Comment by Airblader** [comment]
Don't worry, we have time :) The build broke because the formatting is wrong. Just run clang-format on the changed file and update the commit.

**Comment by kneitinger** [comment]
Okay, I fixed the commit message and corrected the formatting.  I believe I wrote a sufficient test, but I do not feel 100% confident about it.  Does it look correct?

**Comment by kneitinger** [comment]
It can indeed! :D

**Comment by stapelberg** [comment]
I’m hesitant to merge this. As I pointed out in issue #2122, the intended way to use the exec command is to quote the entire argument. I’d even say that it’s not i3’s job to interpret anything you pass to exec, as interpreting shell commands sounds like a road to madness :).

With the clarification in #2122, is there anything that actually _needs_ fixing?

**Comment by kneitinger** [comment]
Yeah that was a super helpful clarification, and avoiding shell command parsing is a great idea! I think the docs are ambiguous as to what needs to be quoted, so that could perhaps use fixing.  Should there perhaps be a test case to verify the intended quoting of commands works?  One with internal, escaped quotes (as discussed in #2122 ) and a comma and semicolon?

**Comment by stapelberg** [comment]
As mentioned in https://github.com/i3/i3/issues/2122#issuecomment-167262810, pull requests are very welcome.

A test case also can’t hurt, so if you’re inclined, please go ahead.

I’ll close this pull request, as it’s obsolete now.

**Pull request closed without merging**
